### ISSUE TITLE
drivers/cc110x: Tracking of future improvements

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#10373]
#### Roadmap

- [x] Rewrite of the base driver https://github.com/RIOT-OS/RIOT/pull/10340
- [ ] Implementation of CCA before transmission as pseudo-module `cc110x_cca`
    - depends on https://github.com/RIOT-OS/RIOT/pull/10340
    - A working proof of concept is here: https://github.com/maribu/RIOT/tree/cc110x_cca
    - Is implemented as pseudo-module, as default ALOHA used less ROM and is fine for many scenarios
    - Update: This needs to be rebased, merge conflicts need to be solved, and I think the `netdev_driver_t::send()` should better block until the channel becomes free (or maybe some bounded wait?). Anyway, I advice against using that branch until it gets reworked
- [ ] Access to the temperature sensor of the transceiver via SAUL as pseudo-module `cc110x_temperature`
    - depends on https://github.com/RIOT-OS/RIOT/pull/10340
    - will only work if GDO0 is connected to pin that can be used as analog input
    - Update: Likely needs some love when the base driver is merged
- [ ] Add pesudo-module `cc110x_autocalibration` to perform automatic re-calibrations of the frequency generator
    - depends on https://github.com/RIOT-OS/RIOT/pull/10340
    - In some scenarios automatic re-calibration of the frequency generator is required, e.g. when temperature is not constant (e.g. outdoor) or the supply voltage changes over time (e.g. when directly connected to a battery)
    - This module will perform re-calibration in configurable intervals, e.g. every 10 minutes

**Comment by PeterKietzmann** [comment]
#10340 got merged a while ago. @maribu I'm gonna close the issue now. In case of leftovers, I suggest to either open a new and more precise feature request issue or reopen this one with an updated description

**Comment by maribu** [comment]
> reopen this one with an updated description

done
