### ISSUE TITLE
Tracker: Vega board porting

### ISSUE THREAD

**Issue by Citrullin** [RIOT-OS/RIOT#10575]
### Porting status

Tasks:

- [ ] Build system config
  - [ ] Cortex-M4 core
  - [ ] Cortex-M0+ core
  - [ ] RI5CY core
  - [ ] ZERO-RISCY core
- [ ] linker scripts
  - [ ] CM4 memory region
  - [ ] CM0+ memory region
- [ ] flashing (openocd support?)
- [ ] boot single core
- [ ] gdb connection
- [ ] reusing kinetis periph drivers
- [ ] UART stdio
- new/unsupported modules:
  - [ ] SCG (clocking)
  - [ ] PCC (module clocks)
  - [ ] LPI2C
  - [ ] LPSPI
  - [ ] LPIT
  - [ ] TRNG (also found in kw41z)
  - [ ] SEMA42
  - [ ] MU
  - [ ] MMDVSQ
- [ ] Radio driver porting (kw41zrf should work with small changes #7107)
- [ ] multi core operation TBD
  - [ ] linking multi core binary for flashing

### Where to find hardware

Now also available outside of the USA: 
https://twitter.com/vegaboardriscv/status/1070765378064633856

The order form is available here:
US residents: https://open-isa.org/order/
Outside US: https://open-isa.org/order/outsideus/

Zephyr already supports RISC-V processors and even the vega board:
https://twitter.com/ZephyrIoT/status/1070393626709159942

And of course, I hope for an integration into RIOT, since I see a huge potential for RISC-V in the future :)

**Comment by gebart** [comment]
Interesting board.
It looks like #7107 might work with this SoC too. I hope I manage to get hold of one of these boards to do some experiments on.

**Comment by aabadie** [comment]
> I hope I manage to get hold of one of these boards to do some experiments on.

+1 here. Looking at the specs, this board is a perfect candidate for joining the other boards in IoT-LAB (Saclay site)

**Comment by gebart** [comment]
@aabadie I was about to @ mention you to ask if you were going to have some of these in the room where all the mixed vendor boards are ;)

**Comment by dylad** [comment]
Wow free boards for real ? Seems really interesting to me !

**Comment by Josar** [comment]
seems to be updated now for outside US https://open-isa.org/order/outsideus/

**Comment by gebart** [comment]
I propose we update this issue into a tracker for the porting effort for the Vega board.

**Comment by Citrullin** [comment]
Maybe [this](https://github.com/zephyrproject-rtos/zephyr/pull/11853) is helpful for the implementation

**Comment by gebart** [comment]
I started outlining a few tasks for the Vega port in the top post

**Comment by gebart** [comment]
My approach to this will be to attempt to get the Cortex-M4 core to run RIOT first, since that should be very similar to simply adding one more Kinetis CPU variant. I believe this MCU may possibly be a close relative to the not yet released K32W0x with extra RISC-V cores.

**Comment by advancedwebdeveloper** [comment]
I have the evaluation board, too. I see that mingw examples is a nightmare - no support for Powershell. I wonder if MSVC's cross-compilation would allow to compile Cortex-M4 targeted examples.

**Comment by dylad** [comment]
@advancedwebdeveloper 
For Windows, if you just want to cross-compile your examples maybe WSL or WSL2 is a good candidate. But I have no out of the box solution for the flashing part.

**Comment by advancedwebdeveloper** [comment]
@dylad , I am on Windows 10 32bit. I do have a Windows 10 64bit machine, nearby - but currently concentrating on 32bit OS.
And nobody answered about Microsoft's support for ARM compiler (MSVC's backend). I heard that it supports 64bit ARM (aarch64).
I thought I could rely more on Powershell scripts. Anyone interested to bootstrap that?
I have created a repo https://github.com/advancedwebdeveloper/rv32m1_sdk_riscv - need to change the license config. We could concentrate our efforts there

**Comment by dylad** [comment]
IIRC, you can setup custom toolchain in Visual Studio, so you can download the ARM toolchain for x86 (32bits) [here](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) and then setup your toolchain in y project configuration.
Regarding powershell scripts I cannot help you unfortunately.

**Comment by dylad** [comment]
(hit the wrong button sorry...)

**Comment by advancedwebdeveloper** [comment]
I suspect that SDKs for https://docs.microsoft.com/en-us/previous-versions/windows/embedded/jj919345%28v%3dwinembedded.80%29 and https://developer.microsoft.com/en-us/windows/iot could be able to offer compilers, for Cortex M4 processor of Vega board.

**Comment by crasbe** [comment]
The website is dead, so I don't think this will go any further...

<img width="1021" height="718" alt="Image" src="https://github.com/user-attachments/assets/4b4f7d7b-f7a9-4457-b0de-e3d670f2d9a5" />
