### ISSUE TITLE
[TRACKING] User interface and reporting tool bugs

### ISSUE THREAD

**Issue by jcarrano** [RIOT-OS/RIOT#10990]
### Description

This issue tracks the progress of bugs related to the user interface to the build system and the way information is reported (for example, errors, toolchain versions, etc.)

The goals are:

- Provide more informative messages that work in every platform.
- Extract enough information about the system to allow proper debugging of issues.

#### Windows

- [ ] toosl/print_toolchain_versions: report windows version #10807 

#### Documentation

- [ ] doxygen/Makefile: summarize warnings, log full output to file. #10976

#### Linux

- [ ] tools/print_toolchain_versions.sh: use lsb_release. #10770 . Some people think it is not a good idea to install the lsb tool, so maybe I'll close this and try to find another way.

#### Other

- [ ] makefiles/color: Add color functions. #10405. This should make colors easier to use for developers.
- [x] tools/ci: correcly report flake8 version. #10252
- [ ] print_toolchain_versions: print system and make's default shell. #10991

**Comment by crasbe** [comment]
While RIOT certainly should have improvements in the user interface, I think this has diverged too far from the current situation to still be relevant.
