### ISSUE TITLE
[TRACKING] sys/shell refactoring.

### ISSUE THREAD

**Issue by jcarrano** [RIOT-OS/RIOT#12105]
#### Description

This is an issue to track enhancements and bugfixes and refactoring of the shell. First bugs must be fixed, then the refactoring should take place.

Bugs:

- [ ] #10635 : fix bug caused by long lines

Enhancements:

- [x] ~#11004 : cancel current line with ctrl-C~
- [ ] #12087 : allow the prompt and echoing to be configure at run-time using special commands.

Refactoring

- [ ] #12085 : rewrite the tokenizer (the part that splits the words in the command line). _This is also a bug fix_ but the original code was way too messy so I just rewrote it.
- [ ] #12099 : similar change to the readline (the part that reads from stdin into an array).

Other:

- [ ] #10788 : Exit the shell on control-D.This one is contested and I'm not sure it is desirable. Actually, ctrl-D is normally handled at another OS layer (which does not exist in RIOT).

Related:

- [ ] #11099 : The raw-terminal is needed if we want to properly test the shell.
- [ ] #9538: argument parser code. This goes _after_ the shell, it would make shell handlers easier to write and less bug-prone.
