### ISSUE TITLE
Failing tests on AVR (tested with atmega256rfr2-xpro)

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/RIOT#12651]
#### Description

Opening this issue for tracking the problems with tests found in #12649. I remove the problems related to interaction with the UART because they should be fixed #12461 and the problem related to network setup with GNRC tests.

Here is the list of failing tests:

- [x] <b>tests/bitarithm_timings</b>: ~~looks like a context switching issue~~ a bug in the test fixed by https://github.com/RIOT-OS/RIOT/pull/12714
  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/bitarithm_timings test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  Start.
  + bitarithm_msb: 102096 iterations per second
  Timeout in expect script at "child.expect('\+ bitarithm_lsb: \d+ iterations per second')" (tests/bitarithm_timings/tests/01-run.py:16)
  ```
  
  </details>

- [x] <b>tests/event_wait_timeout</b>: Fixed in https://github.com/RIOT-OS/RIOT/pull/12776
  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/event_wait_timeout test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  finished: 4/4 events and 1/4 timeouts recorded
  [FAILED]


  main(): This is RIOT! (Version: buildtest)
  [START] event_wait_timeout test application.

  finished: 4/4 events and 1/4 timeouts recorded
  [FAILED]
  Timeout in expect script at "child.expect_exact(u"[SUCCESS]")" (tests/event_wait_timeout/tests/01-run.py:15)
  ```

  </details>

- [x] <b>tests/gnrc_ipv6_fwd_w_sub</b>: timing issue => fixed by #12461 

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/gnrc_ipv6_fwd_w_sub test
  run_test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  > Timeout in expect script at "child.expect(r"Forwarded Ethernet frame:")" (tests/gnrc_ipv6_fwd_w_sub/tests/01-run.py:16)
  ```
  
  </details>

- [ ] <b>tests/gnrc_ndp</b>: no idea of the problems

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/gnrc_ndp test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  ............................
  tests.test_nbr_sol_send__pktbuf_full4 (tests/gnrc_ndp/main.c 552) gnrc_pktbuf_is_empty()
  .
  tests.test_nbr_adv_send__foreign_tgt_unspecified_dst_no_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 571) src != pkt->src
  .
  tests.test_nbr_adv_send__foreign_tgt_unspecified_dst_no_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__foreign_tgt_unspecified_dst_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 568) exp 5 was 0
  .
  tests.test_nbr_adv_send__foreign_tgt_unspecified_dst_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__foreign_tgt_specified_dst_no_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 574) exp 2 was 8
  .
  tests.test_nbr_adv_send__foreign_tgt_specified_dst_no_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__foreign_tgt_specified_dst_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 104
  .
  tests.test_nbr_adv_send__foreign_tgt_specified_dst_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__src_tgt_unspecified_dst_no_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 568) exp 5 was 0
  .
  tests.test_nbr_adv_send__src_tgt_unspecified_dst_no_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__src_tgt_unspecified_dst_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 568) exp 5 was 0
  .
  tests.test_nbr_adv_send__src_tgt_unspecified_dst_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__src_tgt_specified_dst_no_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 574) exp 2 was 8
  .
  tests.test_nbr_adv_send__src_tgt_specified_dst_no_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  .
  tests.test_nbr_adv_send__src_tgt_specified_dst_supply_tl2a_no_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 104
  .
  tests.test_nbr_adv_send__src_tgt_specified_dst_supply_tl2a_ext_opts (tests/gnrc_ndp/main.c 568) exp -1 was 0
  ....
  tests.test_nbr_adv_send__pktbuf_full4 (tests/gnrc_ndp/main.c 763) gnrc_pktbuf_is_empty()
  .
  tests.test_rtr_sol_send__dst_NULL (tests/gnrc_ndp/main.c 784) exp 2 was 0
  .
  tests.test_rtr_sol_send__dst_local (tests/gnrc_ndp/main.c 780) src != pkt->src
  .....
  tests.test_rtr_sol_send__pktbuf_full4 (tests/gnrc_ndp/main.c 886) gnrc_pktbuf_is_empty()
  .
  tests.test_rtr_adv_send__src_NULL_dst_NULL_no_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_NULL_dst_NULL_no_fin_ext_opts (tests/gnrc_ndp/main.c 911) dst != pkt->dst
  .
  tests.test_rtr_adv_send__src_NULL_dst_NULL_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_NULL_dst_NULL_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_NULL_dst_no_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_NULL_dst_no_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_NULL_dst_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_NULL_dst_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_dst_NULL_no_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_dst_NULL_no_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_dst_NULL_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_dst_NULL_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_dst_no_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_dst_no_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  .
  tests.test_rtr_adv_send__src_dst_fin_no_ext_opts (tests/gnrc_ndp/main.c 903) exp 5 was 8647
  .
  tests.test_rtr_adv_send__src_dst_fin_ext_opts (tests/gnrc_ndp/main.c 903) exp -1 was 0
  ....
  tests.test_rtr_adv_send__pktbuf_full4 (tests/gnrc_ndp/main.c 1085) gnrc_pktbuf_is_empty()
  
  run 75 failures 38
  Timeout in expect script at "child.expect(r"OK \(\d+ tests\)")" (tests/gnrc_ndp/tests/01-run.py:16)
  ```
  
  </details>

- [x] <b>tests/isr_yield_higher</b>: Fixed in https://github.com/RIOT-OS/RIOT/pull/12790

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/isr_yield_higher test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  first thread done
  
  
  main(): This is RIOT! (Version: buildtest)
  first thread started
  timer triggered
  TEST FAILED
  first thread done
  Timeout in expect script at "child.expect('TEST SUCCESSFUL')" (tests/isr_yield_higher/tests/test.py:17)
  
  ```
  
  </details>

- [x] <b>tests/libfixmath</b>: fixed by #12687

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/libfixmath test
  r
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  Help: Press s to start test, r to print it is ready
  r
  READY
  s
  START
  Unary.
  abs(-10.0000) = 10.0000
  sq(-10.0000) = 100.0000
  atan(-10.0000) = -1.4989
  
  [...]
  
  min(-4.2500, 1.2500) = -4.2500
  max(-4.2500, 1.2500) = 1.2500
  add(-4.2500, 1.5000) = -2.7500
  sub(-4.2500, 1.5000) = -5.7500
  mul(-4.2500, 1.5000) = -5.8750
  Timeout in expect script at "child.expect('{}\(-?\d+.\d+\) = -?\d+.\d+'.format(op_name))" (tests/libfixmath/tests/01-run.py:14)
  ```
  
  </details>

- [x] <b>tests/pipe</b>: fixed in #12792 

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pipe test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  Start.
  Middle read: <Middle read: <End read: <End read: <Middle read: <Middle read: <End read: <End read: <Middle read: <Middle read: <End read: <End read: <Middle read: <Middle read: <Main done.
  End read: <End read: <Middle read: <Middle done.
  End read: <End done.
  Timeout in expect script at "child.expect_exact('Middle read: <ABCD> [0:4]')" (tests/pipe/tests/01-run.py:9)
  ```
  
  </details>

- [x] <b>tests/pkg_jsmn</b>: Fixed in https://github.com/RIOT-OS/RIOT/pull/12795

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_jsmn test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  - User: - Admin: - UID: - Groups:
  Timeout in expect script at "child.expect_exact('- User: johndoe')" (tests/pkg_jsmn/tests/01-run.py:8)
  ```
  
  </details>

- [x] <b>tests/pkg_lora-serialization</b>: seems like a conversion issue. Maybe this package is not compatible with 8bit architecture. Fixed by #12689

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_lora-serialization test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  Lora Serialization test
  
  Test 1
  Temperature and humidity
  ---------------------------------
  - Writing temperature: 80.12
  - Writing humidity: 99.99
  - Encoded:  1f 4c 0f 27
  - Expected: 1f 4c 0f 27
  ---------------------------------
  SUCCESS
  
  Test 2
  Coordinates and unix time
  ---------------------------------
  - Writing coordinates: -33.905052, 151.26641
  - Writing unix time: 1467632413
  - Encoded:  64 a6 ff ff 60 24 00 00 1d 4b 00 00
  - Expected: 64 a6 fa fd 6a 24 04 09 1d 4b 7a 57
  ---------------------------------
  FAILED
  Timeout in expect script at "child.expect('SUCCESS')" (tests/pkg_lora-serialization/tests/01-run.py:12)
  ```
  
  </details>

- [x] <b>tests/pkg_micro-ecc</b>: fixed in #12797 

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_micro-ecc test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.main(): This is RIOT! (Version: buildtest)
  micro-ecc compiled!
  Testing 16 random private key pairs and signature without using HWRNG
  .
  
  main(): This is RIOT! (Version: buildtest)
  micro-ecc compiled!
  Timeout in expect script at "child.expect_exact('................ done with 0 error(s)')" (tests/pkg_micro-ecc/tests/01-run.py:16)
  ```
  
  </details>

- [x] <b>tests/ps_schedstatistics</b>: too much load in background threads, fixed by #12832

  <details>
  
  ```
  make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/ps_schedstatistics test
  /work/riot/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" --noprefix --no-repeat-command-on-empty-line
  Connect to serial port /dev/ttyACM0
  Welcome to pyterm!
  Type '/exit' to exit.
  
  
  main(): This is RIOT! (Version: buildtest)
  Creating thread #0, next=1
  Creating thread #1, next=2
  Creating thread #2, next=3
  Creating thread #3, next=4
  Creating thread #4, next=0
  
  Timeout in expect script at "child.expect('>')" (tests/ps_schedstatistics/tests/01-run.py:43)
  ```
  
  </details>

- [x] <b> tests/thread_msg_bus/</b>

    <details>
    
    ```
    Help: Press s to start test, r to print it is ready
    READY
    s
    START
    main(): This is RIOT! (Version: 2020.10-devel-18-gab072f-HEAD)
    THREAD 1 start
    THREAD 2 start
    THREAD 3 start
    THREADS CREATED
    Posted event 22 to 0 threads
    Posted event 23 to 0 threads
    Posted event 24 to 0 threads
    SUCCESS
    Timeout in expect script at "child.expect_exact('T1 recv: Hello Threads! (type=23)')" (tests/thread_msg_bus/tests/01-run.py:15)
    
     ```
    </details>

- [x] <b> tests/pkg_libb2/</b>

    <details>

    ```
    2020-07-22 15:07:31,824 # START
    2020-07-22 15:07:31,830 # main(): This is RIOT! (Version: 2020.10-devel-18-gab072f-HEAD)
    2020-07-22 15:07:31,837 # .
    2020-07-22 15:07:31,845 # blake2_tests.test_blake2s (tests/pkg_libb2/main.c 56) memcmp(b2s, hash, sizeof hash) == 0
    2020-07-22 15:07:31,865 # .

    2020-07-22 15:07:31,870 # Help: Press s to start test, r to print it is ready

     ```
    </details>

#### Steps to reproduce the issue

Run the following command:

```
$ BUILD_IN_DOCKER=1 ./dist/tools/compile_and_test_for_board/compile_and_test_for_board.py . atmega256rfr2-xpro --jobs=4 --with-test-only
```

#### Expected results

All tests succeed. Unsupported tests (for good reasons) are skipped.

#### Actual results

Some tests are failing.

#### Versions

Versions from riotbuild docker image.

**Comment by aabadie** [comment]
For `tests/pkg_lora-serialization`, there's a portability problem with 8bit architectures. https://github.com/leandrolanzieri/lora-serialization/pull/1 is not completely solving the failing test (because there are apparently also floating point precision issues) but is already an improvement I think.
The floating point issue can be solved by using an adapted expected test array in the case where AVR GCC is used.

**Comment by maribu** [comment]
I was able to fix `tests/ps_schedstatistics` via this:

```patch
diff --git a/tests/ps_schedstatistics/main.c b/tests/ps_schedstatistics/main.c
index 7d2f9de6d3..ce95fad7b5 100644
--- a/tests/ps_schedstatistics/main.c
+++ b/tests/ps_schedstatistics/main.c
@@ -45,7 +45,7 @@ static void *_thread_fn(void *arg)
         for (int i = 0; i < (10 * (next + 1)); ++i) {
             _xtimer_now64();
         }
-        xtimer_usleep(XTIMER_BACKOFF * 3);
+        xtimer_usleep(XTIMER_BACKOFF * 30);
         msg_send(&m2, pids[next]);
     }
 ```

Those threads just created too much load for an ATmega to handle, so that the main thread was starving. I have the feeling that just generally reducing the load will not be ideal for benchmarking ARM boards. (I checked this on top of the fix in #12790, but I believe that this is unrelated really just caused by the load.)

**Comment by fjmolinas** [comment]
I think the reason `tests/ps_schedstatistics` is failing is because of un-proper `XTIMER_BACKOFF` , see #11522 and #11546. It is also the case for `frdm-kw41z`

**Comment by maribu** [comment]
I'm not so sure that this is the sole reason. `_xtimer_now64()` is **way** more expensive in terma of CPU cycles on ATmega.

I guess that a value for `XTIMER_BACKOFF` that would allow the test to pass would be so high, that we get regressions elsewhere. E.g. some apps might have to threads which both periodically get executed with a short period. If `XTIMER_BACKOFF` gets to high, the other thread might strave.

But I'll happily give it a try to see by how much the backoff needs to be increased to get the test working. If the value doesn't get super high, this would indeed be the better fix.

**Comment by aabadie** [comment]
@miri64, do you have any idea of what could be the problem with `tests/gnrc_ndp` on AVR boards (see details in the 4th point of this issue) ?

**Comment by miri64** [comment]
No, not really. The test is working as expected on ARM Cortex :-/ and I don't really have an AVR board at hand right now nor the time to investigate this. For the `gnrc_pktbuf_is_empty()` fails I would at least use `gnrc_pktbuf_stats()` first to check what is the packet stuck in the packet buffer, for the others (if available) I would use the debugger.

**Comment by aabadie** [comment]
Regarding `ps_schedstatistics`, even when changing XTIMER_BACKOFF from 3 to 10, it's working on `atmega256rfr2-xpro` and `arduino-mega2560`. On a samr21-xpro, I can also see some load on the different threads. So maybe increasing the XTIMER_BACKOFF value to 10 would be enough ?

**Comment by aabadie** [comment]
@maribu, I opened #12832 because I'd like to move forward with `tests/ps_schedstatistics` on AVR. Threre are other problems with xtimer but I think that we should not block the test to succeed on AVR because of this.

**Comment by fjmolinas** [comment]
I have another failing test on avr, `tests/thread_msg_bus`, tested on `arduino-mega2560` and `atmega256rfr2-xpro`:

```
main(): This is RIOT! (Version: 2020.10-devel-18-gab072f-HEAD)
THREAD 1 start
THREAD 2 start
THREAD 3 start
THREADS CREATED
Posted event 22 to 0 threads
Posted event 23 to 0 threads
Posted event 24 to 0 threads
SUCCESS
Timeout in expect script at "child.expect_exact('T1 recv: Hello Threads! (type=23)')" (tests/thread_msg_bus/tests/01-run.py:15)
```

@benpicco can you take a look?

**Comment by fjmolinas** [comment]
I updates the issue.

**Comment by fjmolinas** [comment]
I have another failing test on avr, `tests/pkg_libb2`, tested on `arduino-mega2560` and `atmega256rfr2-xpro`:

```
2020-07-22 15:07:30,503 # Help: Press s to start test, r to print it is ready
s
2020-07-22 15:07:31,824 # START
2020-07-22 15:07:31,830 # main(): This is RIOT! (Version: 2020.10-devel-18-gab072f-HEAD)
2020-07-22 15:07:31,837 # .
2020-07-22 15:07:31,845 # blake2_tests.test_blake2s (tests/pkg_libb2/main.c 56) memcmp(b2s, hash, sizeof hash) == 0
2020-07-22 15:07:31,865 # .

2020-07-22 15:07:31,870 # Help: Press s to start test, r to print it is ready
```

Updated list again.

**Comment by fjmolinas** [comment]
`tests/ps_schedstatistics` is failing again as well.

**Comment by chudov** [comment]
I have successful test `tests/thread_msg_bus` on `derfmega256`:

    main(): This is RIOT! (Version: 2021.04-devel-661-g6b8cb)
    THREAD 1 start
    THREAD 2 start
    THREAD 3 start
    THREADS CREATED
    Posted event 22 to 0 threads
    T1 recv: Hello Threads! (type=23)
    T3 recv: Hello Threads! (type=23)
    Posted event 23 to 2 threads
    T2 recv: Hello Threads! (type=24)
    Posted event 24 to 1 threads
    SUCCESS

**Comment by chudov** [comment]
Regarding `pkg_libb2`: 8bit architectures are not supported by libb2. 
@fjmolinas Seems it make sense to exclude `tests/pkg_libb2` from the list.

**Comment by fjmolinas** [comment]
> I have successful test `tests/thread_msg_bus` on `derfmega256`:
> 
> ```
> main(): This is RIOT! (Version: 2021.04-devel-661-g6b8cb)
> THREAD 1 start
> THREAD 2 start
> THREAD 3 start
> THREADS CREATED
> Posted event 22 to 0 threads
> T1 recv: Hello Threads! (type=23)
> T3 recv: Hello Threads! (type=23)
> Posted event 23 to 2 threads
> T2 recv: Hello Threads! (type=24)
> Posted event 24 to 1 threads
> SUCCESS
> ```

Yes, I have the same result seems this stopped failing somewhere along the way.

**Comment by fjmolinas** [comment]
> > I have successful test `tests/thread_msg_bus` on `derfmega256`:
> > ```
> > main(): This is RIOT! (Version: 2021.04-devel-661-g6b8cb)
> > THREAD 1 start
> > THREAD 2 start
> > THREAD 3 start
> > THREADS CREATED
> > Posted event 22 to 0 threads
> > T1 recv: Hello Threads! (type=23)
> > T3 recv: Hello Threads! (type=23)
> > Posted event 23 to 2 threads
> > T2 recv: Hello Threads! (type=24)
> > Posted event 24 to 1 threads
> > SUCCESS
> > ```
> 
> Yes, I have the same result seems this stopped failing somewhere along the way.

Actually the PR is linked the list was never updated, #14582

**Comment by fjmolinas** [comment]
> pkg_libb2

Yes, that would make sense, do you have a pointer to where the supported arch are specified?

**Comment by aabadie** [comment]
Regarging libb2, this was "fixed" in #15513 (because indeed this package doesn't support 8bit)

**Comment by aabadie** [comment]
So there's only `tests/gnrc_ndp` that's still failing and TBH I have no idea what is the cause.

**Comment by fjmolinas** [comment]
> Regarging libb2, this was "fixed" in #15513 (because indeed this package doesn't support 8bit)

Ah thanks!

**Comment by fjmolinas** [comment]
Nice!

**Comment by aabadie** [comment]
Thanks for the last fix @miri64 !
