### ISSUE TITLE
[CTF-tracker] Kconfig: Configuration exposure list

### ISSUE THREAD

**Issue by leandrolanzieri** [RIOT-OS/RIOT#12888]
#### Description
This will issue will track the progress of the exposure of module's configurations to Kconfig.

For now the list contains the modules that have already identified their configurations by adding them to Doxygen's `config` group, but it will be extended. The idea on the first phase is to keep the 
default method of configuration as is (through header files and CFLAGS) and model that into Kconfig file for each module.

---

#### Drivers
- [ ] ADCXX1C driver compile configurations
- [ ] mrf24j40 driver compile configuration
- [ ] WDT compile configurations

#### System
- [ ] USB peripheral compile time configurations
##### Networking
- [ ] GNRC
    - [ ] GNRC 6LoWPAN compile configurations
    - [ ] GNRC IPv6 NIB compile configurations
    - [ ] GNRC IPv6 address blacklisting compile configurations
    - [ ] GNRC IPv6 address whitelisting compile configurations
    - [ ] GNRC IPv6 compile configurations
    - [ ] GNRC network interface configurations
- [ ] Gcoap compile configurations (#12887)
- [ ] CoAP compile configurations
- [ ] IEEE802.15.4 compile configurations
- [ ] IPv6 extension header compile configurations
- [ ] LoRa modulation compile configurations
- [ ] LoRaMAC compile configurations
- [ ] Nanocoap compile configurations
- [ ] SOCK utility functions compile configurations

#### CPUs
- [ ] ESP common compile configurations
- [ ] ESP32 compile configurations
- [ ] ESP8266 compile configurations

#### Packages
- [ ] NanoCBOR configuration header
- [ ] Tinydtls compile time configuration
- [ ] Wakaama LwM2M Client configuration
- [ ] Wakaama LwM2M platform adaption

### Useful links
[Documented configurations](http://doc.riot-os.org/group__config.html)

**Comment by MrKevinWeiss** [comment]
Instead of opening another issue I will piggyback off this one...

I have a messy script to try to get an idea of what is out there:
https://gist.github.com/MrKevinWeiss/671f28b06eb0a478d5d2ce1640dc5bdf

There are some things missing (specifically downloaded packages) but at least it is a start.

https://github.com/RIOT-OS/RIOT/issues/20437 might want to be aware of this...

And finally, https://github.com/RIOT-OS/RIOT/pull/20438 should contain some fixes or at least a pre-step in order to complete the config list.
