### ISSUE TITLE
periph/timer: `timer_set()` underflow safety check (tracking issue)

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#13072]
#### Description

#13060 added timer_set() protection from IRQ.

There are a couple of other implementations that need to be reviewed for irq safety (found with `git grep 'int.*timer_set('`):

- [ ] esp32/periph/timer.c (two impls.)
- [ ] esp8266/periph/timer.c (two impls)
- [ ] fe310/periph/timer.c
- [ ] kinetis/periph/timer.c
- [ ] mips32r2_common/periph/timer.c

IMO we should take a close look at all of them. Also, confirm whether they're actually needed or can just be replaced by the generic one.

All four esp implementation seem to internally protect from irqs. @gschorcht maybe confirm?

**Comment by gschorcht** [comment]
> All four esp implementation seem to internally protect from irqs. @gschorcht maybe confirm?

Confirmed :wink:
