### ISSUE TITLE
[Tracking] cc13x2_cc26x2 drivers support

### ISSUE THREAD

**Issue by jeandudey** [RIOT-OS/RIOT#13635]
#### Description

This issue is intended to track progress for the support of the `cc13x2_cc26x2` and the features that need to be implemented.

- [ ] Add a `SetupTrimDevice` implementation. This should be called after the hardware bootloader finishes boot and starts the firmware (`cpu_init`). It sets some registers to good defaults.
  - [Reference implementation](https://github.com/contiki-ng/coresdk_cc13xx_cc26xx/blob/0d78d3280357416a5c0388148cda13717c9ffaa5/source/ti/devices/cc13x2_cc26x2/driverlib/setup.c#L113)
- [ ] Use ROM driverlib code to reduce binary size. The CC26xx/CC13xx MCUs have a minimal implementation of the TI SDK driverlib to reduce binary size with common code.
  - [ROM API definitions](https://github.com/contiki-ng/coresdk_cc13xx_cc26xx/blob/36ce7ddf1535f49ec55abfbd2c5180fa34320edb/source/ti/devices/cc13x2_cc26x2/driverlib/rom.h)
- [ ] RF driver. Still being worked on #13295 . WIP
- [ ] MTD implementation for flash memory.
- [ ] Compiling and linking CCFG.
  - [ ] Explore the usage of the bootloader backdoor to use a script like [cc2538-bsl](https://github.com/JelmerT/cc2538-bsl) (should work of the box if I'm not mistaken)
- [ ] SPI driver.
   - [ ] MTD driver for MX25xx SPI flash included in SimpleLink launchpads.
      - [MX25xx datasheet](https://www.components-store.com/datasheets/a5/MX25R8035FZUIH1.pdf)
- [ ] I2C driver. `cc26x0` already has an implementation, that code can be generalized and put under `cc26xx_cc13xx`.

### Useful links

- [Versioned CC26xx/CC13xx SDK](https://github.com/contiki-ng/coresdk_cc13xx_cc26xx)
- [CC13x2, CC26x2 TRM](https://www.ti.com/lit/ug/swcu185d/swcu185d.pdf)
