### ISSUE TITLE
Tracker: improve GNRC netif module

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#13763]
## Description

This issue summarizes the ongoing effort of improving the GNRC network interface (`gnrc_netif_t`) and surrounding mechanisms.
This was originally in the scope of the #12688, but I decided to split it in a different scope to make it easier to follow.

The goal is to provide a more efficient integration of link layers into GNRC, optimize the usage of RAM in cases with more than one interface and have a more reliable IRQ processing from network devices.

# Related PRs/issues

- [x] Dynamic GNRC_NETIF_NUMOF (#12994)
- [ ] Reduce the number of `gnrc_netif` threads (#13762)
- [ ] gnrc netif dependent to netdev (#13614)
- [ ] Use `thread_flags` based mechanisms to process IRQs (e.g `event_loop` in the `gnrc_netif_thread`) (https://github.com/RIOT-OS/RIOT/pull/13669)
