### ISSUE TITLE
Tracker: Kconfig: Model features provided by CPU and Board

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#14148]
## Description

It was decided during the Virtual Maintainers Assembly 2020.05 to continue with the next phases of the Kconfig migration. This means that Kconfig will be used to model all module’s configurations and dependencies in the build system.

The first milestone is to model all features provided by CPUs and boards. Also explicitly declare and document all the possible features that can be provided and used.

This milestone doesn’t interfere with the current Kconfig integration nor the build system, so it can be performed directly on the master branch. In order to keep the features in sync in the Makefile.features and the Kconfig files, a static check will be added, which will be run for every PR.

## What needs to be done
- Declare Feature symbols: Analog to the current build system, features like HAS_PERIPH_SPI, HAS_PERIPH_GPIO or HAS_RIOTBOOT have to be declared. Check the Annex for the full list of features
- Declare CPUs and boards common symbols: Each CPU and module should declare common symbols to track the hardware in compile time. See "Modelling CPU" and "Modelling boards" for more information.
- Select the provided features by CPUs and boards: Each CPU and Board should select the supported feature symbols.

https://github.com/RIOT-OS/RIOT/pull/13404 can be used as a reference.

## Tracker
Also check the GitHub [project](https://github.com/RIOT-OS/RIOT/projects/27).

- [x] Declare feature symbols (Common symbols in #14151)
- [x] Add static check (#13404)
- [x] CPUs
    - [x] cc1312r1f3
    - [x] cc1352p1
    - [x] cc1352r1
    - [x] cc2538sf53 (#14343)
    - [x] cc26x0f128
    - [x] cc430f6137
    - [x] efm32 (#14310)
      - [x] efm32gg990f1024
      - [x] efm32lg990f256
      - [x] efm32pg12b500f1024gl125
      - [x] efm32pg1b200f256gm48
      - [x] efr32mg1p132f256gm32
      - [x] efr32mg1p132f256gm48
    - [x] esp32 (#14223)
    - [x] esp8266 (#14223)
    - [x] ezr32wg330f256r60 (#14388)
    - [x] fe310 (#14338)
    - [x] LM4F120H5QR (#14469)
    - [x] lpc1768 (#14470)
    - [x] lpc2388 (#14471)
    - [x] mk20dx256vlh7 (#14421)
    - [x] mk22fn512vlh12 (#14421)
    - [x] mk64fn1m0vll12 (#14421)
    - [x] mk41z (#14421)
    - [x] msp430 (#14340)
    - [x] nrf51 (#14440)
    - [x] nrf52 (#14440)
    - [x] p32mx470f512h (#14475)
    - [x] p32mz2048efg100 (#14475)
    - [x] sam3x8ede16a (#14477)
    - [x] same54p20a (#14483)
    - [x] samd21 (#13404)
    - [x] saml1x (#14485)
    - [x]  saml21 (#14487)
    - [x] stm32 (#14525)

- [x] Boards (common symbols + feature selection)
   - [x] 6lowpan-clicker (#14475)
   - [x] acd52832 (#14440)
   - [x] adafruit-clue (#14440)
   - [x] airfy-beacon (#14440)
   - [x] arduino-due (#14477)
   - [x] arduino-duemilanove (#14176)
   - [x] arduino-leonardo (#14195)
   - [x] arduino-mega2560 (#14211)
   - [x] arduino-mkr1000 (#14189)
   - [x] arduino-mkrfox1200 (#14189)
   - [x] arduino-mkrwan1300 (#14189)
   - [x] arduino-mkrzero (#14189)
   - [x] arduino-nano (#14176)
   - [x] arduino-nano-33-ble (#14440)
   - [x] arduino-uno (#14176)
   - [x] arduino-zero (#14189)
   - [x] atmega1284p (#14208)
   - [x] atmega256rfr2-xpro (#14206)
   - [x] atmega328p (#14176)
   - [x] avr-rss2 (#14206)
   - [x] avsextrem (#14471)
   - [x] b-l072z-lrwan1 (#14525)
   - [x] b-l475e-iot01a (#14525)
   - [x] blackpill (#14525)
   - [x] blackpill-128kib (#14525)
   - [x] bluepill (#14525)
   - [x] bluepill-128kib (#14525)
   - [x] calliope-mini (#14440)
   - [x] cc1312-launchpad (#14210)
   - [x] cc1352-launchpad (#14210)
   - [x] cc1352p-launchpad (#14210)
   - [x] cc2538dk (#14343)
   - [x] cc2650-launchpad (#14210)
   - [x] cc2650stk (#14210)
   - [x] chronos (#14340)
   - [x] derfmega128 (#14203)
   - [x] derfmega256 (#14206)
   - [x] dwm1001 (#14440)
   - [x] ek-lm4f120xl (#14469)
   - [x] esp32-heltec-lora32-v2 (#14223)
   - [x] esp32-mh-et-live-minikit (#14223)
   - [x] esp32-olimex-evb (#14223)
   - [x] esp32-ttgo-t-beam (#14223)
   - [x] esp32-wemos-lolin-d32-pro (#14223)
   - [x] esp32-wroom-32 (#14223)
   - [x] esp32-wrover-kit (#14223)
   - [x] esp8266-esp-12x (#14223)
   - [x] esp8266-olimex-mod (#14223)
   - [x] esp8266-sparkfun-thing (#14223)
   - [x] f4vi1 (#14525)
   - [x] feather-m0 (#14189)
   - [x] feather-nrf52840 (#14440)
   - [x] firefly (#14343)
   - [x] fox (#14525)
   - [x] frdm-k22f (#14421)
   - [x] frdm-k64f (#14421)
   - [x] frdm-kw41z (#14421)
   - [x] hamilton (#14189)
   - [x] hifive1 (#14338)
   - [x] hifive1b (#14338)
   - [x] i-nucleo-lrwan1 (#14525)
   - [x] ikea-tradfri (#14310)
   - [x] im880b (#14525)
   - [x] iotlab-a8-m3 (#14525)
   - [x] iotlab-m3 (#14525)
   - [x] limifrog-v1 (#14525)
   - [x] lobaro-lorabox (#14525)
   - [x] lsn50 (#14525)
   - [x] maple-mini (#14525)
   - [x] mbed_lpc1768 (#14470)
   - [x] mcb2388 (#14471)
   - [x] mega-xplained (#14208)
   - [x] microbit (#14440)
   - [x] microduino-corerf (#14203)
   - [x] msb-430 (#14340)
   - [x] msb-430h (#14340)
   - [x] msba2 (#14471)
   - [x] msbiot (#14525)
   - [x] mulle (#14421)
   - [x] native (#14538)
   - [x] nrf51dk (#14440)
   - [x] nrf51dongle (#14440)
   - [x] nrf52832-mdk (#14440)
   - [x] nrf52840-mdk (#14440)
   - [x] nrf52840dk (#14440)
   - [x] nrf52840dongle (#14440)
   - [x] nrf52dk (#14440)
   - [x] nrf6310 (#14440)
   - [x] nucleo-f030r8 (#14525)
   - [x] nucleo-f031k6 (#14525)
   - [x] nucleo-f042k6 (#14525)
   - [x] nucleo-f070rb (#14525)
   - [x] nucleo-f072rb (#14525)
   - [x] nucleo-f091rc (#14525)
   - [x] nucleo-f103rb (#14525)
   - [x] nucleo-f207zg (#14525)
   - [x] nucleo-f302r8 (#14525)
   - [x] nucleo-f303k8 (#14525)
   - [x] nucleo-f303re (#14525)
   - [x] nucleo-f303ze (#14525)
   - [x] nucleo-f334r8 (#14525)
   - [x] nucleo-f401re (#14525)
   - [x] nucleo-f410rb (#14525)
   - [x] nucleo-f411re (#14525)
   - [x] nucleo-f412zg (#14525)
   - [x] nucleo-f413zh (#14525)
   - [x] nucleo-f429zi (#14525)
   - [x] nucleo-f446re (#14525)
   - [x] nucleo-f446ze (#14525)
   - [x] nucleo-f722ze (#14525)
   - [x] nucleo-f746zg (#14525)
   - [x] nucleo-f767zi (#14525)
   - [x] nucleo-l031k6 (#14525)
   - [x] nucleo-l053r8 (#14525)
   - [x] nucleo-l073rz (#14525)
   - [x] nucleo-l152re (#14525)
   - [x] nucleo-l412kb (#14525)
   - [x] nucleo-l432kc (#14525)
   - [x] nucleo-l433rc (#14525)
   - [x] nucleo-l452re (#14525)
   - [x] nucleo-l476rg (#14525)
   - [x] nucleo-l496zg (#14525)
   - [x] nucleo-l4r5zi (#14525)
   - [x] nz32-sc151 (#14525)
   - [x] olimexino-stm32 (#14525)
   - [x] opencm904 (#14525)
   - [x] openlabs-kw41z-mini (#14421)
   - [x] openlabs-kw41z-mini-256kib (#14421)
   - [x] openmote-b (#14343)
   - [x] openmote-cc2538 (#14343)
   - [x] p-l496g-cell02 (#14525)
   - [x] p-nucleo-wb55 (#14525)
   - [x] particle-argon (#14440)
   - [x] particle-boron (#14440)
   - [x] particle-xenon (#14440)
   - [x] pba-d-01-kw2x (#14421)
   - [x] phynode-kw41z (#14421)
   - [x] pic32-wifire (#14475)
   - [x] pinetime (#14440)
   - [x] pyboard (#14525)
   - [x] reel (#14440)
   - [x] remote-pa (#14343)
   - [x] remote-reva (#14343)
   - [x] remote-revb (#14343)
   - [x] ruuvitag (#14440)
   - [x] samd21-xpro (#14189)
   - [x] same54-xpro (#14483)
   - [x] saml10-xpro (#14485)
   - [x] saml11-xpro (#14485)
   - [x] saml21-xpro (#14487)
   - [x] samr21-xpro (#13404)
   - [x] samr30-xpro (#14487)
   - [x] samr34-xpro (#14487)
   - [x] seeeduino_arch-pro (#14470)
   - [x] sensebox_samd21 (#14189)
   - [x] serpente (#14189)
   - [x] slstk3401a (#14310)
   - [x] slstk3402a (#14310)
   - [x] sltb001a (#14310)
   - [x] slwstk6000b-slwrb4150a (#14310)
   - [x] slwstk6000b-slwrb4162a (#14310)
   - [x] slwstk6220a (#14388)
   - [x] sodaq-autonomo (#14189)
   - [x] sodaq-explorer (#14189)
   - [x] sodaq-one (#14189)
   - [x] sodaq-sara-aff (#14189)
   - [x] sodaq-sara-sff (#14189)
   - [x] spark-core (#14525)
   - [x] stk3600 (#14310)
   - [x] stk3700 (#14310)
   - [x] stm32f030f4-demo (#14525)
   - [x] stm32f0discovery (#14525)
   - [x] stm32f3discovery (#14525)
   - [x] stm32f429i-disc1 (#14525)
   - [x] stm32f4discovery (#14525)
   - [x] stm32f723e-disco (#14525)
   - [x] stm32f769i-disco (#14525)
   - [x] stm32l0538-disco (#14525)
   - [x] stm32l476g-disco (#14525)
   - [x] teensy31 (#14421)
   - [x] telosb (#14340)
   - [x] thingy52 (#14440)
   - [x] ublox-c030-u201 (#14525)
   - [x] udoo (#14477)
   - [x] usb-kw41z (#14421)
   - [x] waspmote-pro (#14208)
   - [x] wsn430-v1_3b (#14340)
   - [x] wsn430-v1_4 (#14340)
   - [x] yunjia-nrf51822 (#14440)
   - [x] z1 (#14340)

**Comment by aabadie** [comment]
I edited this issue with #14525

**Comment by leandrolanzieri** [comment]
Awesome!
