### ISSUE TITLE
IPv6 Path MTU discovery in GNRC

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#14396]
#### Description
Given that we are starting to get a variety of link-layer types with varying defined IPv6 MTUs, we should start thinking about implementing [Path MTU Discovery](https://tools.ietf.org/html/rfc8201). Most of the ground work is already done, just some components missing.

- [x] Send Packet Too Big message to sender when device MTU is too big:
  https://github.com/RIOT-OS/RIOT/blob/028c0d4b3cf80d5c0f4350105cd238984a37abd5/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L263-L268
- [ ] Extend NIB off-link entries with Path MTU (PMTU):
  https://github.com/RIOT-OS/RIOT/blob/028c0d4b3cf80d5c0f4350105cd238984a37abd5/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h#L198-L220
- [x] Cache destination on next-hop determintation:
  https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L272-L274
- [ ] Provide destination cache view for NIB that also provides the PMTU. There [exists already a `_DC` flag for off-link entries](https://github.com/RIOT-OS/RIOT/blob/028c0d4b3cf80d5c0f4350105cd238984a37abd5/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h#L56) and even [internal functions to fill it](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.h#L589-L627), it is just not exposed to be used within `gnrc_ipv6`.
- [ ] Handle Packet Too Big received message and store PMTU in destination cache:
  https://github.com/RIOT-OS/RIOT/blob/028c0d4b3cf80d5c0f4350105cd238984a37abd5/sys/net/gnrc/network_layer/icmpv6/gnrc_icmpv6.c#L86-L111
- [ ] Use PMTU from destination cache to engage fragmentation, not local MTU:
  https://github.com/RIOT-OS/RIOT/blob/028c0d4b3cf80d5c0f4350105cd238984a37abd5/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c#L459-L466

### Useful links
- Originally part of https://github.com/RIOT-OS/RIOT/issues/1647
- Also discussed here https://github.com/RIOT-OS/RIOT/pull/14172
- [RFC 4861 Sending Algorithmus](https://tools.ietf.org/html/rfc4861#section-5.2) that involves destination cache creation
- [RFC 8201](https://tools.ietf.org/html/rfc8201) specifies Path MTU Discovery
- The (incomplete) [model description of the NIB](https://miri64.github.io/riot-ndp-model/)
