### ISSUE TITLE
Save Time in Travis

### ISSUE THREAD

**Issue by LudwigKnuepfer** [RIOT-OS/RIOT#1636]
A couple of installation steps could be faster.
- [ ] skip locale generation or reduce to one locale
- [x] installation iterations can be combined (https://github.com/RIOT-OS/RIOT/pull/1691)
- [x] use apt caching (#1689)
- [ ] ask Travis maintainers to include missing repo(s)
- [x] fail on test fail (https://github.com/RIOT-OS/RIOT/issues/1636#issuecomment-55290967)
- [ ] use download cache (#1692)
- [ ] more ?

**Comment by OlegHahm** [comment]
I guess this becomes a wontfix, too.
