### ISSUE TITLE
board:cpu: RIOT port for the atsamr21xpro board

### ISSUE THREAD

**Issue by thomaseichinger** [RIOT-OS/RIOT#1646]
List to coordinate porting efforts for the samr21xpro board and it's samd21 cpu.
Please leave a comment what you are working on to mark it in the list and 
open pull requests against ~~https://github.com/thomaseichinger/RIOT/tree/samr21~~ master branch.

Porting todos:
- [x] basic file structure @thomaseichinger
- [x] cortex-m0_common usage @thomaseichinger
- [x] scripts for flashing/debuging (needs newest [openocd from git](https://repo.or.cz/openocd.git)) @thomaseichinger
- [x] LED marcos @thomaseichinger
- [x] set F_CPU correctly
- [x] LPM - under review #2309 @LudwigOrtmann @saurabh984 (cpu has periph/pm)
- [x] peripheral drivers
  - [x] UART @thomaseichinger, @Troels51 
  - [x] timer @thomaseichinger, @Troels51 
  - [x] GPIO @Troels51, @thomaseichinger
  - [x] cpuid @wiredsource 
  - [x] SPI  @Troels51 
  - [x] I2C @bapclenet
  - [x] rtt @daniel-k #2918 
  - [x] rtc @bapclenet 
  - [x] pwm ~~#2473~~ #3127 @haukepetersen 
  - [x] adc - under review ~~#2063 @wiredsource~~  ~~#4162 @msolters~~ Done in #7009
  - [x] random number generator (RNG) (#4989)
  - [x] PLL @haukepetersen #3034 
- [x] radio driver, done, at86rf2xx @haukepetersen ~~(at86rf231 driver works for now, will get at86rf2xx) @thomaseichinger @Troels51~~  
- [x] [wiki documentation](https://github.com/RIOT-OS/RIOT/wiki/Board:-Samr21-xpro) @haukepetersen

**Comment by saurabh984** [comment]
Any one fancy trying the LPM code for me please?? Literally wrote this on Github's editor on my iPad so can't test it :disappointed: 

```
/*
 * Copyright (C) 2014 Freie Universität Berlin
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @ingroup     cpu_samd21
 * @{
 *
 * @file        lpm_arch.c
 * @brief       Implementation of the kernels power management interface
 * 
 * @author      Thomas Eichinger <thomas.eichinger@fu-berlin.de>
 *
 * @}
 */
#include "cpu.h"
#include "arch/lpm_arch.h"

enum system_sleepmode {
	/**
	 *  Idle 0 mode.
	 *  Potential Wake Up sources: Synchronous(APB, AHB), asynchronous.
	 */
	SYSTEM_SLEEPMODE_IDLE_0,
	/**
	 *  Idle 1 mode.
	 *  Potential Wake Up sources: Synchronous (APB), asynchronous
	 */
	SYSTEM_SLEEPMODE_IDLE_1,
	/**
	 *  Idle 2 mode.
	 *  Potential Wake Up sources: Asynchronous
	 */
	SYSTEM_SLEEPMODE_IDLE_2,
	/**
	 * Standby mode.
	 * Potential Wake Up sources: Asynchronous
	 */
	SYSTEM_SLEEPMODE_STANDBY,
};

static enum lpm_mode current_mode;

void lpm_arch_init(void)
{
    current_mode = LPM_ON;
}

enum lpm_mode lpm_arch_set(enum lpm_mode target)
{
enum lpm_mode last_mode = current_mode;

    switch (target) {
        case LPM_ON:                    /* Run mode */
            current_mode = LPM_ON;
            break;
        case LPM_IDLE:                  /* Sleep mode Idle 0 */
            current_mode = LPM_IDLE;
            /* Idle Mode 0 */
            SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk;
            PM->SLEEP.reg = SYSTEM_SLEEPMODE_IDLE_0;
            start_lpm();
            break;
        case LPM_SLEEP:                 /* Sleep mode Idle 1 */
            current_mode = LPM_SLEEP;
             /* Idle Mode 1 */
            SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk;
            PM->SLEEP.reg = SYSTEM_SLEEPMODE_IDLE_1;
            start_lpm();
            break;
        case LPM_POWERDOWN:             /* Sleep mode Idle 2 */
            /* Idle Mode 2 */
            SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk;
            PM->SLEEP.reg = SYSTEM_SLEEPMODE_IDLE_2;
            start_lpm();
            break;
        case LPM_OFF:                   /* Standby Mode - Potential Wake Up sources: Asynchronous */
            current_mode = LPM_POWERDOWN;
            /* Standby Mode */
            SCB->SCR |=  SCB_SCR_SLEEPDEEP_Msk;
            start_lpm();
            break;
        default:
            break;
    }

    return last_mode;
}

static void start_lpm(void) 
{
	/* Executes a device DSB (Data Synchronization Barrier) */
    __DSB();
    /* Enter standby mode */
    __WFI();
}

enum lpm_mode lpm_arch_get(void)
{
    return current_mode;
}

void lpm_arch_awake(void)
{
    if (current_mode == LPM_SLEEP) {
        /* Re-init */
        cpu_init();
    }
    current_mode = LPM_ON;
}

/** Not needed */
void lpm_arch_begin_awake(void){ }

/** Not needed */
void lpm_arch_end_awake(void){ }
```

**Comment by LudwigOrtmann** [comment]
Compiles after adding `static void start_lpm(void);` ;)

**Comment by saurabh984** [comment]
Thanks @LudwigOrtmann :laughing: You can create a PR if you like! This adds SAM R21 LPM features  - All 4 modes the CPU supports

**Comment by LudwigOrtmann** [comment]
I couldn't try if it actually works because I didn't have time to get openocd running for this board yet .. I'll create a PR.

**Comment by LudwigOrtmann** [comment]
here it is https://github.com/RIOT-OS/RIOT/pull/2309

**Comment by saurabh984** [comment]
Thanks @LudwigOrtmann

**Comment by songjw0820** [comment]
Info : SAMD MCU: SAMR21G18A (256KB Flash, 32KB RAM)
wrote 32768 bytes from file /home/user/RIOT-master/examples/hello-world/bin/samr21-xpro/hello-world.hex in 40.885929s (0.783 KiB/s)
Error: CMSIS-DAP: Read Error (0x07)
Error: CMSIS-DAP: Write Error (0x07)
Warn : target was in unknown state when halt was requested
Error: CMSIS-DAP: Write Error (0x07)
Error: CMSIS-DAP: Write Error (0x07)
Error: error executing cortex_m crc algorithm
Error: CMSIS-DAP: Write Error (0x07)
Error: CMSIS-DAP: Write Error (0x07)
Error: Failed to read memory and, additionally, failed to find out where
in procedure 'verify_image'
make: *** [flash] Error 1

**Comment by thomaseichinger** [comment]
@songjw0820 could you please provide us your openocd version? Does this happen with every attempt to flash? Reading your log it seems to be the actual writing did succeed, do you see any output when connecting over serial line?

**Comment by songjw0820** [comment]
@thomaseichinger Thank you for your answer!
Open On-Chip Debugger 0.9.0-dev-00268-ga9c90a0
yse flash.Serial no output...

**Comment by thomaseichinger** [comment]
@songjw0820 I was able to flash the board successfully with this exact version of openocd. Could you tell us a little more about you environment? (OS, version, are you using a virtual machine?) Do you have a second board to try flashing?

**Comment by songjw0820** [comment]
@thomaseichinger yse virtual machine, ubuntu 14.04.

**Comment by songjw0820** [comment]
@thomaseichinger I tried another demonstration boards today, run a successfully

**Comment by bapclenet** [comment]
I'm not working on RNG for the moment, if anyone wants to go on, here is a start:
https://github.com/bapclenet/RIOT/blob/samr21/RNG/cpu/samd21/periph/random.c
It uses the AT86RF233 random bits. As of now, it uses AT86RF231 driver since at86rf2xx is not yet implemented.

@thomaseichinger, could you add the issue related to at86rf2xx driver?
Remove my name on RNG and ADC as I stopped working on please.
Thanks

**Comment by dantheman2865** [comment]
Hey guys, I've been messing around with the SAMR21-XPRO boards and I haven't been able to get the "sixlowpan" app to work. Maybe related, but I've noticed (now using the "default" app) that if I use the "pan" command to set the pan and then use "txtsnd" to send a message, the message is always received on pan 1. Could these be related? Any ideas? 
Also, I can submit a PR or somebody else can fix it, but lines 91-96 in at86rf321.c suffer from a copy-pasta error.
Thanks for all of your hard work, I'm looking forward to diving in!

**Comment by LudwigOrtmann** [comment]
Regarding this board/transceiver and problems with network: Please search the mailing lists and issue tracker, there is plenty of text on this topic.

**Comment by kYc0o** [comment]
it still needs this issue to be open?

**Comment by OlegHahm** [comment]
ADC, PRNG and LPM are still missing.

**Comment by kYc0o** [comment]
Ok, I just updated the ADC work being done by another person.

**Comment by kYc0o** [comment]
I'll milestone too since I think we can get it fully supported for the next release

**Comment by kYc0o** [comment]
Didn't make it, so postponing.

**Comment by miri64** [comment]
> ADC, PRNG and LPM are still missing.

Is there another PRNG than #4989 on that board?

**Comment by OlegHahm** [comment]
Anyone working on the ADC driver?

**Comment by PeterKietzmann** [comment]
@immesys wanted to

**Comment by immesys** [comment]
I did some work on it, I discovered that many use cases we had required tweaking things like gain, differential sampling and whatnot, so now I have this conflict between making a simple, abstraction-compatible ADC driver and one that implements all the platform specific features. I will do my best on it, and then I may need some shepherding. Timeline is probably 3 weeks though

**Comment by kaspar030** [comment]
I've checked LPM and the rng. Seems like we finally have a fully supported board!

Feel free to reopen if you disagree.

**Comment by thomaseichinger** [comment]
3 years and 1 month. 😀

Congratulations to everybody contributing and perusing this.
(FYI removed the WIP label)
