### ISSUE TITLE
Make layer 3 MTU board dependent

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#1647]
The MTU is currently defined layer dependent, but for some boards it is just to big. This issue proposes to make it board-dependent. When you're at it: make all packet buffers MTU dependent.

Things to do:
- [ ] implement [path MTU discovery](http://tools.ietf.org/html/rfc1981) for IPv6
- [ ] are their similar mechanisms for other protocols (CCN-lite, ...)?
- [ ] add MTU macro to all `cpu_conf.h`
- [ ] make packet buffers MTU dependent

**Comment by authmillenon** [comment]
I would say this is a device dependent thing, but implementing PMTU discovery is still something of interest

**Comment by miri64** [comment]
@haukepetersen can you maybe look into this?

**Comment by kaspar030** [comment]
> implementing PMTU discovery is still something of interest

Isn't the path MTU in IPv6 defined to be at least 1280b?

Anyhow, can we close this?

**Comment by miri64** [comment]
Yapp, but @OlegHahm used to want smaller MTUs. For non-routing hosts this can also be totally valid an in the confines of the standard (it doesn't send packets bigger than the size it is comfortable with and just drops anything too big).

**Comment by miri64** [comment]
Let's close this after all. It does not seem sensible to me anymore to follow this on (except for the Path MTU Discovery part)

**Comment by miri64** [comment]
Opened https://github.com/RIOT-OS/RIOT/issues/14396 for the PMTU part of this issue.
