### ISSUE TITLE
setup bors (tracking issue)

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#18911]
This issue is for tracking the setup of bors for our CI.

Non-invasive, preparatory:
- [x] make ci.riot-os.org build "testing" and "trying"
- [x] add RIOT-OS/RIOT to bors
- [x] add bors.toml: https://github.com/RIOT-OS/RIOT/pull/18910

Switch over:
- [x] implement quick build for PR / full build for "testing" in `./.murdock`: https://github.com/RIOT-OS/RIOT/pull/18956
- [x] change "master" branch protection to only require the "bors" status
- [x] make bors mandatory for merging (disables manual merges)

Fixing:
- [x] backport necessary bors/murdock configuration to current release branch

**Comment by maribu** [comment]
@kaspar030: Ping?

**Comment by kaspar030** [comment]
Migration considered done. I've moved the planned optimizations to another issue: #19092
