### ISSUE TITLE
CI: optimizations (tracking issue)

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#19092]
#### Description

Optimizations:
- [ ] allow multiple parallel builds on ci.riot-os.org (so PR builds don't have to wait for "testing" builds)
  - [ ] enable on ci.riot-os.org
  - [ ] support multiple prioities (more than "normal" and "fasttracked") in murdock-ng
    - [ ] use priority queue instead of two regular queues: https://github.com/murdock-ng/murdock/pull/18
    - [ ] allow setting priority through other means than "fasttracked" label
  - [ ] make murdock dwq backend prioritize PR jobs
