### ISSUE TITLE
[tracking] unnessesary use of floating point arithmetics

### ISSUE THREAD

**Issue by maribu** [RIOT-OS/RIOT#19614]
#### Description

There have been a number of issues (https://github.com/RIOT-OS/RIOT/issues/17486 and https://github.com/RIOT-OS/RIOT/issues/12045 are still open) on use of floating point arithmetic. This tries to bundle the effort in a single place

List of offenders:

- [ ] drivers/adt7310
- [ ] drivers/apds99xx
- [ ] drivers/at30tse75x
- [ ] drivers/at30tse75x
- [ ] drivers/bme680
- [ ] drivers/hih6130
- [ ] drivers/isl29125
- [ ] drivers/lpsxxx https://github.com/RIOT-OS/RIOT/pull/19609
- [ ] drivers/mpu9x50
- [ ] drivers/mq3
- [ ] drivers/scd30
- [ ] drivers/sps30
- [ ] drivers/sx127x
- [ ] drivers/tmp00x
- [ ] sys/color

**Comment by kfessel** [comment]
rg -e '\d\.\d' |rg -iv license | rg -ive ':\s*/?\*'
