### ISSUE TITLE
ci: tracking: migrate to github merge trains

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#20051]
This issue tracks the migration to github merge trains. Will update as we go along.

- [x] make murdock build merge train branches #20052
- [x] create branch `merge_queue_migration`, try to get the workflows to fly there
    - [x] enable merge queues in RIOT repo (for `merge_queue_migration`)
    - [x] fix "slow static-tests" #20061
    - [x] drop "limit build" commit
- [ ] enable merge queues for master && PR `merge_queue_migration` to master #20063 
- [x] update branch protections
- [ ] stop murdock builds of cancelled merge_group runs

follow up:
- [ ] solve merge_group for release branches
- [ ] remove bors configuration

**Comment by MrKevinWeiss** [comment]
Note: When removing a PR from the mq, it appears that murdock still tries to finish building instead of cancelling.  Maybe this is due to not listening to `merge_groups_mirgration` branch and only master.  Maybe we need to listen to the `gh-readonly-queue/*` branch closing.  Somehow we need to cancel the murdock job when removing PRs from the queue.

**Comment by MrKevinWeiss** [comment]
It seems force pushing something to a PR that is already in a mq does not remove the mq branch from the queue

**Comment by MrKevinWeiss** [comment]
We still need to verify that the branch protection rules are set so that a merge train is possible and what happens to the other PRs when one fails.

**Comment by maribu** [comment]
I think this can be closed, can't it?
