### ISSUE TITLE
[tracking] Improve failure tolerance in driver/mtd_spi_nor

### ISSUE THREAD

**Issue by crasbe** [RIOT-OS/RIOT#20769]
#### Description

The work in #20589 uncovered a lot of possible improvements for driver/mtd_spi_nor.
Especially in it's current form it is not very resiliant against failing operations or non-responsive devices, leading to loops and essentially a hanging program.

- [ ] When mtd_spi_nor_power tries to read the JEDEC ID and fails and no timers are used, it will retry 560,000,000 times to read the JEDEC ID, which takes a _considerable_ amount of time, essentially blocking the system from startup. The variable "retries" has to be set to a sensible value.
- [ ] There is no timeout for the functions wait_for_write_enable_cleared and wait_for_write_enable_set, which would get the thread stuck if the chip does not answer. https://www.macronix.com/Lists/Datasheet/Attachments/8868/MX25R6435F,%20Wide%20Range,%2064Mb,%20v1.6.pdf Page 34 has a block diagram. Macronix says to issue the WREN command again if the flag has not been set. So the right thing to do isn't waiting for the flag to be set but retrying (for a finite amount of times).
- [ ] The function wait_for_write_complete does not have a timeout either but it counts the attempts and how many times it yielded the thread. This can be used as a basis for a timeout. The timeout should be dependent on the operation, chip erase can take a very long time (in the multiple minutes range), whereas other operations shouldn't take very long.
- [ ] Add a software fallback for the data integrity functions (to check if the program or erase was successful). Depending on the length of the operation, maybe only do some random checks to avoid doing a full blank check of a 128MB chip for example.
- [ ] Patch the nRF52840DK board mtd.c to utililze the data integrety checks by default. Depends on #20589.

The first three points are probably a single PR, the fourth one is a single PR and the last one as well.
