### ISSUE TITLE
Network stack refactoring: TODO list

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#2278]
Next steps (as result from the network stack task force meeting):

All new modules are to be prepended with the prefix `ng_`.

 - [x] define protocol types (@authmillenon) [merged -> #2397]
 - [x] implement packet abstraction (@authmillenon) [merged -> #2342]
 - [x] define configuration types (@haukepetersen) [merged -> #2399]
 - [x] define netdev interface (@haukepetersen) [merged -> #2398]
 - [x] define netapi interface (@haukepetersen) [merged -> #2400]
 - [x] implement packet buffer (@authmillenon) [merged -> #2285]
 - [x] define and implement netreg (@authmillenon) [merged -> #2404]
 - [x] define a generic link layer header (@haukepetersen) [merged -> #2449]
 - [x] adjust nomac MAC layer (@haukepetersen) [merged -> #2426]
 - [x] remodel at86rf2xx driver (@haukepetersen) [merged -> #2825]
 - [x] adjust nativenet to netdev ~~(@authmillenon) [under review -> #2558]~~ (@kaspar030) [merged -> #2766]
 - ~~adjust netdev dummy (@haukepetersen)~~ [postponed]
 - [x] add network interface module (@authmillenon) [merged -> #2417]
 - [x] get IPv6 to run (@authmillenon) [merged -> #2454]:
   - [x] Address architecture [merged -> #2433]
   - [x] IPv6 Interfaces [merged -> #2437]
   - [x] neighbor cache [merged -> #2461]
   - [x] extension headers [merged -> #2898]
 - [x] reimplement ICMPv6 (@authmillenon) [under review -> #2555]
 - [x] get NDP to run (@authmillenon)
   - [x] Address resolution [merged -> #2910]
   - [x] Router discovery ~~[WIP -> #2612]~~ [merged -> #3049]
 - [ ] reimplement 6LoWPAN as seperate module (@authmillenon)
  - [x] raw IPv6 [merged -> #2614]
  - [x] fragmentation [merged -> #2781]
  - [x] IPHC [merged -> #2806]
  - [ ] NHC
  - [x] NDP optimization [merged -> #3134]
 - [x] define and implement FIB (@bytesgalore) [merged -> #2211]
 - [x] ~~adjust RPL to new FIB (@bytesgalore) [under review -> #2765]~~ [this was for the old RPL implementation]
 - [x] reimplement RPL (@cgundogan) [under review -> #3050]
 - [ ] adjust AODV to new FIB (@lotterleben) [under review -> #3445]
 - [x] reimplement UDP (@haukepetersen) [merged -> #2430]
 - [ ] reimplement TCP (@brummer-simon) [under review -> #2827]
 - [x] add shell commands for new API (@haukepetersen) [merged -> #2525]

Open topics
 - adjust CC2420 radio
 - adjust CC1100 radio
 - [ ] ICMPv6 error messages [under review -> #3184]
 - Redirect behavior of NDP
 - [x] reimplement sockets [merged -> #3646]

**Comment by authmillenon** [comment]
@OlegHahm can we please use the Network Stack Task Force Milestone only for PR's that are explicitly mentioned in this list? Otherwise we risk getting people easily confused.

**Comment by authmillenon** [comment]
The last critical component was merged. From now on it's Happy Hacking!

**Comment by OlegHahm** [comment]
> @OlegHahm can we please use the Network Stack Task Force Milestone only for PR's that are explicitly mentioned in this list? Otherwise we risk getting people easily confused.

Ah, haven't seen this before. Will do.

**Comment by authmillenon** [comment]
> @OlegHahm can we please use the Network Stack Task Force Milestone only for PR's that are explicitly mentioned in this list? Otherwise we risk getting people easily confused.

Just a little update on my rational for assigning the milestone: PR's or features that are explicitly mentioned here and any fix- or follow-up to those.

**Comment by authmillenon** [comment]
Updated list.

**Comment by miri64** [comment]
Though there are still some things under construction, since PRs exist I would deem this issue as complete, so close.
