### ISSUE TITLE
features lost when removing obsolete network stack

### ISSUE THREAD

**Issue by kaspar030** [RIOT-OS/RIOT#3417]
This issue is supposed to track features that will be removed by #3334.
Feel free to update.

(marked means, work on gnrc version has started)

- [x] posix sockets
- [x] TCP
- [ ] AODV (#3445)
- [ ] ~~OLSR~~
- [x] NHDP (uses socket_base, fixed in #3876)
- [X] RPL (#3050 et. al)
  - (subparts of RPL?)
- [x] cc11xx support (#3716)
- [ ] cc2420 support (#3915)
- [ ] ~~econotag-support (though it wasn't very stable to begin with)~~
- [x] CCN-lite
- [x] mainpage.txt transceiver documentation
- [x] oonf API (uses `socket_base`, and is used by NHDP, fixed in #3882)

*edited by @OlegHahm:* OLSR was never part of RIOT master.

**Comment by authmillenon** [comment]
@cgundogan might shed some light on the status of `ng_rpl`, @Lotterleben how far is AODV on that front, @benpicco and @OlegHahm what about OLSR?

**Comment by OlegHahm** [comment]
OLSR was never merged anyway.

**Comment by OlegHahm** [comment]
@kaspar030, what about ccn-lite?

**Comment by authmillenon** [comment]
And OpenWSN?

**Comment by OlegHahm** [comment]
@thomaseichinger is adapting it to the new driver anyway. Hopefully finished this week.

**Comment by Lotterleben** [comment]
@authmillenon  @BytesGalore and I have started to port AODVv2 yesterday (and have merged the the PR integrating the FIB today)... I have no idea how smoothly this will go, but I'll keep you posted.

**Comment by haukepetersen** [comment]
I think TCP is under construction, right @brummer-simon?

**Comment by brummer-simon** [comment]
Yes it is.

**Comment by authmillenon** [comment]
Added NHDP as it uses `socket_base` (which has no source files now).

**Comment by OlegHahm** [comment]
A shiny new CCN-Lite version has just been merged.

**Comment by authmillenon** [comment]
\o/

**Comment by kaspar030** [comment]
Does anyone still care about this?

**Comment by OlegHahm** [comment]
I think the only thing that was part of the old stack that is still missing, is TCP support, right? And AFAIK this is hopefully ready soon. Hence, Fine with closing this one.

**Comment by kaspar030** [comment]
Yup.
