### ISSUE TITLE
List of compiling issues on OS X

### ISSUE THREAD

**Issue by kYc0o** [RIOT-OS/RIOT#6473]
I just ran

```bash
for i in $(ls); do if [[ -d "$i" ]]; then echo $i;  make -C $i; fi;  done;
```

on the RIOT tests folder to know which things are free of error on OS X, and that gave results which can be useful

  - [x] **tests_can** fixed in #7847.
```console
/Users/facosta/git/RIOT-OS/RIOT/sys/can/conn/isotp.c:67:18: error: comparison of integers of different signs: 'int' and 'unsigned int'
      [-Werror,-Wsign-compare]
/Users/facosta/git/RIOT-OS/RIOT/sys/shell/commands/sc_can.c:41:23: error: comparison of integers of different signs: 'int' and
      'unsigned int' [-Werror,-Wsign-compare]
    for (int i = 0; i < CAN_DLL_NUMOF; i++) {
                    ~ ^ ~~~~~~~~~~~~~
/Users/facosta/git/RIOT-OS/RIOT/sys/shell/commands/sc_can.c:64:15: error: comparison of integers of different signs: 'int' and
      'unsigned int' [-Werror,-Wsign-compare]
    if (ifnum >= CAN_DLL_NUMOF) {
        ~~~~~ ^  ~~~~~~~~~~~~~
/Users/facosta/git/RIOT-OS/RIOT/sys/shell/commands/sc_can.c:94:15: error: comparison of integers of different signs: 'int' and
      'unsigned int' [-Werror,-Wsign-compare]
    assert(ifnum < CAN_DLL_NUMOF);
           ~~~~~ ^ ~~~~~~~~~~~~~
    if (ifnum >= CAN_DLL_NUMOF) {
        ~~~~~ ^  ~~~~~~~~~~~~~
/Users/facosta/git/RIOT-OS/RIOT/core/include/assert.h:105:11: note: expanded from macro 'assert'
    if (!(cond)) { \
          ^~~~
1 error generated.
3 errors generated.
```
  - [ ] **driver_hd44780** Errors due to the spefici setting for Arduino. I propose to white list the boards which support Arduino pin mapping.
  - [ ] **gnrc_ipv6_nib** Found a _pontential_ corner case @miri64 : 
```console
/Users/facosta/git/RIOT-OS/RIOT/sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c:269:20: error: unused function '_get_l2addr_from_ipv6'
      [-Werror,-Wunused-function]
static inline void _get_l2addr_from_ipv6(uint8_t *l2addr,
                   ^
1 error generated.
```
  - [ ] **gnrc_ipv6_nib_6ln** Unused function error (another potential corner case):
```console
/Users/facosta/git/RIOT-OS/RIOT/sys/net/gnrc/network_layer/ipv6/nib/nib.c:543:20: error: unused function '_is_reachable'
      [-Werror,-Wunused-function]
static inline bool _is_reachable(_nib_onl_entry_t *entry)
                   ^
1 error generated.
```
  - [x] **ssp** buffer overflow detected. Fixed in #7777 
```console
/Users/facosta/git/RIOT-OS/RIOT/tests/ssp/main.c:33:5: error: '__builtin___memset_chk' will always overflow destination buffer
      [-Werror,-Wbuiltin-memcpy-chk-size]
    memset(buf, 0, 32);
    ^~~~~~~~~~~~~~~~~~
/usr/include/secure/_string.h:77:3: note: expanded from macro 'memset'
  __builtin___memset_chk (dest, val, len, __darwin_obsz0 (dest))
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
  - [x] **unittests** Works! Fixed for release 2017.10
  - [x] **saul** Why it works? Does native provide support for SAUL? It works according to [comment](https://github.com/RIOT-OS/RIOT/issues/6473#issuecomment-275916905)

**Comment by basilfx** [comment]
> pkg_u8g2 Why it works? Is it possible to use it in native?

There are four output backends, of which the first redirects to stdout, the second to SDL, the third to SPI and the fourth to I2C.

**Comment by kYc0o** [comment]
>There are four output backends, of which the first redirects to stdout, the second to SDL, the third to SPI and the fourth to I2C.

>First two can run on native without problems.

Super, I'll mark it as done.

**Comment by smlng** [comment]
@kYc0o please not that with #6444 and #6599 the default board for certain boards changed. Which means, that even without supplying a specific board via `BOARD=<something>` some tests will use e.g. `BOARD=samr21-xpro` instead of `native`. Specifically this holds for most periph tests, that require SPI or I2C <- not available for `native` (yet).

That said: as I use macOS myself and do also care about those (nasty) compile errors or warnings: could you please update your list. Many issues are resolved in the mean time anyway, so could also be reasonable to close this one (for now).

**Comment by kYc0o** [comment]
I removed non-related OS X errors from the list according to @smlng [comment](https://github.com/RIOT-OS/RIOT/issues/6473#issuecomment-306437140).

However I still found errors and proposed a fix for one of them. @miri64 can you check the ipv6 related ones?

I'll open another issue for board related errors found by clang.

**Comment by miri64** [comment]
> However I still found errors and proposed a fix for one of them. @miri64 can you check the ipv6 related ones?

Will do after the release.

**Comment by kYc0o** [comment]
AFAIK all these issues were addressed, there are new ones but I'll open another issue with them. Closing.
