### ISSUE TITLE
periph/i2c: tracking the remodeling

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#6577]
The changes proposed in #6575 and #6576 need many efforts to be undertaken. This issue will track the progress and should help to synchronize the work efforts.

Modules in RIOT that need adaption:
CPUS:
- [x] atmega_common (@mali #9252 )
- [x] efm32 (@basilfx #9208)
- [x] nrf51 (@aabadie #9477)
- [x] nrf52 (@dylad #9334)
- [x] cc2538 (@smlng #9347 )
- [x] kinetis (@gebart #9262)
- [x] sam0_common (@dylad #9198)
- [x] stm32 (@aabadie #9202 )

DRIVERS AND TESTS:
- [x] adcxx1c (@vincent-d #9210)
- [x] ads101x (#9165)
- [x] adxl345 (@dylad)
- [x] at30tse75x (@aabadie #9229)
- [x] bh1750fvi (@MichelRottleuthner #9494)
- [x] bmx055 (@smlng #9466)
- [x] bmx280 (maybe @haukepetersen with #8383, @basilfx #9206 for the time being)
- [x] bmp180 (@aabadie #9228)
- [x] ds1307 (@MichelRottleuthner #9493)
- [x] fxos8700 (@gebart #9268)
- [x] hdc1000 (@Hyungsin #9455)
- [x] hih6130 (@gebart #9270)
- [x] hts221(@aabadie ) new one => #9298
- [x] ina220 (@gebart, #9269)
- [x] isl29020 (@aabadie, #8688 )
- [x] isl29125 (@MichelRottleuthner, #9392)
- [x] jc42 (@MichelRottleuthner #9492)
- [x] l3g4200d (@aabadie, #8698)
- [x] lc709203f (@MichelRottleuthner #9481)
- [x] lis3mdl (@aabadie #9276)
- [x] lps331ap (@aabadie, #8757 )
- [x] lsm303dlhc (@aabadie, #8699 )
- [x] lsm6dsl (@aabadie ) => new one #9299
- [x] mag3110 (@aabadie, #8758)
- [x] mma8x5x (@vincent-d #9265 )
- [x] mpl3115a2 (@aabadie #9275)
- [x] mpu9150 (@aabadie #9277)
- [x] pn532 (@MichelRottleuthner, ~~#9432~~ #9458)
- [x] si114x (@aabadie #9314)
- [x] si70xx (@basilfx #9205)
- [x] srf02 (@MrKevinWeiss, #9423)
- [x] srf08 (@MrKevinWeiss, #9422)
- [x] tcs37727 (@aabadie, #8683 )
- [x] tmp006 (@Hyungsin #9457)
- [x] tsl2561 (@aabadie, #8673 )
- [x] veml6070 (@aabadie #9278)

TESTS:
- [x] periph_i2c (@MrKevinWeiss #9168)
- [x] add auto test and refinement (@MrKevinWeiss #9409)

PACKAGES:
- [x] u8g2 (@basilfx #9207)

**Comment by dylad** [comment]
just one remark, adxl345 driver is missing from the list.

**Comment by ZetaR60** [comment]
@haukepetersen ads101x update: #9165

**Comment by vincent-d** [comment]
For stm32, we should try to come up with a unified driver.
It seems that there are 2 different IPs:
 - stm32f1, stm32f2, stm32f4, stm32l1
 - stm32f0, stm32f3, stm32f7, stm32l0, stm32l4

So 2 versions of the driver should be written.

**Comment by aabadie** [comment]
@vincent-d, +1 for unifying the drivers but it seems simpler/harmless to do it in a second step. Is it ok for you ?

**Comment by vincent-d** [comment]
I would say it's easier to do it straight. But of course, I would develop with only 1 arch first and adapt afterwards. 
But the current situation with a driver per sub-family where most of them are just copy/paste is crap.

**Comment by aabadie** [comment]
Ok @vincent-d, you convinced me. See #9202 for the L0 and F3. I don't know how to cleanly set the internal speed options and how to unify with the second type of drivers (F0/F2/F4/F7/L1). Are you ok to work on this part ?

**Comment by gebart** [comment]
I will try to do the Kinetis implementation during the weekend

**Comment by dylad** [comment]
Great !! Many thanks @gebart !:+1:

**Comment by MrKevinWeiss** [comment]
Just FYI, 

I am testing with the new i2c API and a samr21 board,

the new API says the return of i2c read/writes should be error codes ( I2C_ACK, I2C_ADDR_NACK...) but they are return the number of bytes.

Also the read bytes and read reg seem to be physically reading one too many: i2c_read_bytes(addr, 4, 0) actually reads 5 bytes (according to the oscilloscope) but says it reads 4.

**Comment by dylad** [comment]
> the new API says the return of i2c read/writes should be error codes ( I2C_ACK, I2C_ADDR_NACK...) but they are return the number of bytes.

In fact, when we implemented the proposed I2C API, we also look at the current implementation of SPI. I guess the number of bytes read or written is borrowed from the SPI and we didn't take in account the I2C_ACK return code.
Both solutions can be applied we just need a consensus I guess :)

Regarding the extra byte read, as I remember this issue is also true in the previous API. We need to ensure this issue only exists for SAM0 CPUs. I'll try to fix whenever I can but it can also be fix later if it's only impacting SAM0.

**Comment by gebart** [comment]
What about slave mode? 
This would be a good time to at least think about where slave mode will fit in the API.
Since i2c is a multimaster bus, the API should be designed in a way that a device can act both as a master and a slave on the same bus.

**Comment by dylad** [comment]
> What about slave mode?

TBH, I don't really think about it but you're right, this may be a good timing to start some discussions about like how the slave API will look like ? 
Regarding multimaster bus, I've personally never used it. Do we know if there are some existing, working and open-source implementations somewhere ?
This may fit in another issue.

**Comment by gebart** [comment]
One more open issue:
How do we configure timeout limits for when the slave holds the clock low for too long?

**Comment by dylad** [comment]
What about create a device attribute as params ? Or maybe add a hardcoded value per driver ?

**Comment by aabadie** [comment]
@dylad, #9202 (STM32 I2C driver) has rebase issue with new_i2c_if because #7658 (DMA) was merged after the embargo and it conflicts with #9202 since they touch the same files.
I'm wondering what it the best strategy to solve this. Should we rebase new_i2c_if branch on top of master now ? or backport #7658 to new_i2c_if ? or something else ?

**Comment by dylad** [comment]
This is where the fun begins.
I guess we should rebase the new_i2c_if branch. It's probably better than push a revert which will re-revert right ?

**Comment by aabadie** [comment]
> we should rebase the new_i2c_if branch

I would do that as well, because this is what will happen in the end. Maybe @miri64 will have some advice, since she already managed the netif feature branch.

If we do the rebase, the next question is: do we want to keep the merge commit in the rebased branch (using --preserve-merges) or not ?

**Comment by aabadie** [comment]
>  I'm not a git expert.
No problem.
The current RIOT workflow in GitHub creates merge commits each time one hits the GitHub green button.
So for example the new_i2c_if branch contains all merge commits created when we merged PRs containing updates of I2C API and drivers (have a look at the git history, merge commits have 2 ancestors commits - for other git experts, let's keep it simple for now).
But when one rebases a branch with merge commits (here new_i2c_if) on top of another branch (here it would be master), the default behaviour of git is to remove them. Instead, you can force git to try to also reapply the merge commits using the `--preserve-merges` option.
Personally, I would vote for removing the merge commits (I don't like it, I prefer a linear history).

**Comment by dylad** [comment]
Well I guess I will leave this question to our zealots :)
TBH I understand the situation but I don't have strong opinion.

**Comment by miri64** [comment]
> Maybe @miri64 will have some advice, since she already managed the netif feature branch.

If you don't want to loose merge commits (and there identity) the way to go would be to merge master into the branch, but this should have been prevented by the embargo. So the cleanest way would be to revert or backport the commits that cause the conflict/are required.

**Comment by dylad** [comment]
> So the cleanest way would be to revert or backport the commits that cause the conflict/are required

But if we revert something, we will need to re-revert it once we merge the whole branch right ? isn't weird ?

**Comment by aabadie** [comment]
Thanks @miri64. Is it ok if we cherrypick commits from #7658 in new_i2c_if ?

**Comment by miri64** [comment]
> But if we revert something, we will need to re-revert it once we merge the whole branch right ? isn't weird ?

Yes, but that's what we did for gnrc_netif/gnrc_ipv6_nib as well.

> Thanks @miri64. Is it ok if we cherrypick commits from #7658 in new_i2c_if ?

I'd rather like you to open backport commits, so the history is trackable in both git and GitHub.

**Comment by dylad** [comment]
We need to take a decision about the I2C return code within the API.
Should we return I2C_ACK (aka 0) or the number of bytes read/written ?
I guess the latter may help when debugging. This is also the current behaviour of the SPI bus.

What do you think ?

**Comment by aabadie** [comment]
+1 for the number of bytes

**Comment by dylad** [comment]
Ok after some debate with myself, I change my mind.I  think we should drop the number of bytes read/written.
I2C is synchronous bus. We're not supposed to read more bytes by design and if we read/write less, the function will return an error code like. 
I also took another look to the SPI implementation. The behaviour is not that clear to me and return the return is not always used (some functions return void)

**Comment by MrKevinWeiss** [comment]
I will just put some things I noticed regarding that issue:
- The only time the number of bytes would differ from length is an error (maybe you can think of adding timeout and collision errors), meaning that the number of bytes should never return any non error that is not equal to length
- RPi i2c c library seems to return the number of bytes (but I think it is because they use a filesystem write) but doesn't use error codes (so if error it a read will return 0)
- It is possible to support useful error codes (if all error codes are constrained to negative numbers) and number of bytes written
- in higher level drivers the number of bytes to write/read and number of bytes written/read are a property of the device structure.

**Comment by dylad** [comment]
Adding error codes to the API is something trivial as we can implement them later in the CPU drivers.

> The only time the number of bytes would differ from length is an error (maybe you can think of adding timeout and collision errors), meaning that the number of bytes should never return any non error that is not equal to length

Some driver already implements timeout or lost arbitration on the bus. So I guess it's probably more useful to improve our error codes. If something is wrong on the bus, we will return the dedicated error code and if everything is alright, what's the point on returning the number of bytes written or read as we already knew it and pass it as an argument ?

Dropping the return number of bytes will force us to make more changes in devices driver but this is for our sake right ? :)

**Comment by MrKevinWeiss** [comment]
>  If something is wrong on the bus, we will return the dedicated error code and if everything is alright, what's the point on returning the number of bytes written or read as we already knew it and pass it as an argument? 

Agreed, I don't think there should ever be cases that we wouldn't get an error but would have a different number of bytes.

> Dropping the return number of bytes will force us to make more changes in devices driver but this is for our sake right?

Heh, I didn't think of it like that but it makes sense.  Most things use this as 0 is an error, now that it is success it will be easier to detect. I guess the question is try to keep some compatibility which might have small unknown errors or make it blatant and propagate changes everywhere.

**Comment by aabadie** [comment]
> RPi i2c c library seems to return the number of bytes (but I think it is because they use a filesystem write) but doesn't use error codes (so if error it a read will return 0)

I looked at the I2C api of other MCU OSes (Zephyr/MyNewt/Nuttx) and they all use return codes (0: success, negative values in case of errors, some use errno return codes). None are using the number of bytes read/written. So this goes into @dylad direction.

**Comment by dylad** [comment]
If we're agreed then we will take this direction.
Using errno could be interesting but is this already used in RIOT ? I never saw it but it already covers 99% of use case.
Most of the work is locate in the device driver. We can still add new I2C error code now (or after this refactoring) in the API, which is not harmful to any drivers and add support for this new error code in CPU driver.
I will take a look at all currently implemented I2C driver today. Then we can discuss adding new error code (like timeout, lost arbitration etc.). If most of the previous CPU driver already support support it then we can add new error code, if not this will be done later as CPU driver improvement.

if you have any idea on useful error code, feel free to post it :) This idea is to use all of this to ease debugging.

**Comment by aabadie** [comment]
> Using errno could be interesting but is this already used in RIOT ?

I think netdev, can, saul apis are using them and there are occurrences in the native related code.

What about -EIO (IO errors), -ENXIO (no such device or address), -ETIMEDOUT ?

**Comment by dylad** [comment]
So the current I2C_ADDR_NACK will be replaced by -ENXIO but what about I2C_DATA_NACK ? replaced by -EIO ?

**Comment by MrKevinWeiss** [comment]
+1 +1 +1 to errno!

**Comment by gebart** [comment]
+1 for errno, but the common codes _must_ be explained in the function docs (no data ACK, no addr ACK, timeout, and so on). Otherwise each cpu implementation is likely to use different codes for the same condition.

**Comment by gebart** [comment]
One of the requested features in a api rework is the ability to do repeated starts. There are weird devices which use multiple repeated starts as part of their protocol.
I think the function you posted just needs to change flags & no stop to flags| no stop

**Comment by dylad** [comment]
@gebart is right, you probably using an old version of the API because we saw this error and `flags & I2C_NOSTOP` has been replaced by `flags | I2C_NOSTOP` already.

**Comment by MrKevinWeiss** [comment]
I still think there may be an issue, what about if it was (flags | NOSTOP & NOSTART) since the first write must always write the start and the second write should either NOSTART for the majority of sensor or have a start in case of repeated start.  Sound OK?

**Comment by MrKevinWeiss** [comment]
> you are probably using an old version of the API

Changing so fast!

**Comment by dylad** [comment]
> Changing so fast!

This is a fast growing child !

We can clear the NOSTART flag by default for the first call but I don't think we should change the second call.
Don't forget theses functions are just here for basic, generic, and non-weird I2C sensors. If we implement weird I2C stuff later, the device driver will have to implement its own read/write function using i2c_read_bytes and i2c_write_bytes with the flags which give much more flexibility.

**Comment by MrKevinWeiss** [comment]
(flags | NOSTOP & ~NOSTART) sorry

**Comment by MrKevinWeiss** [comment]
Can anyone think of a case where we would need I2C_NOSTOP or I2C_NOSTART with read_bytes command?  If not than I think I got a bug free ;) solution that works with the SAMR21 and fits the API.

**Comment by gebart** [comment]
It would be good to have periph_init run after uart_stdio has been initialized. My debug prints in init are causing the system to crash because of uninitialized stdio... I'll remove them for now

**Comment by dylad** [comment]
@gebart I'm not against, in fact that would be logical. But this doesn't belong to the I2C refactoring as they are plenty of way for doing it. Maybe opening an issue is a better idea. I don't think all maintainers/developers are looking at this issue.

**Comment by dylad** [comment]
I take a look at the Linux kernel documentation -> [here](https://www.kernel.org/doc/Documentation/i2c/fault-codes)
I propose to use the following errno's code : 
-EIO -> I2C_DATA_NACK ?, 
-ENXIO -> equivalent to the current I2C_ADDR_NACK, 
-ETIMEDOUT ->  timeout occurs before device's response
-EOPNOTSUPP -> use when a flag or operation is not supported by the driver
-EAGAIN -> lost bus arbitration (when another master take the lead of the bus)

What do you think ? Did I miss a case ?

**Comment by gebart** [comment]
@dylad 
I have used -EINVAL in other places when there were invalid arguments passed to functions, such as flags. How about EINVAL instead of EOPNOTSUPP?

**Comment by gebart** [comment]
This is a bit late, but changing the CPU periph api into three primitives would make it possible to reuse a larger part of the logic as periph_common instead of reimplementing in each CPU. The primitives would be start, transmit, and receive. Where the transmit or receive functions would perform a stop unless a flag is sent. This way we could place all of the logic for 10 bit addressing inside periph_common and the cpu drivers would not need to bother with anything but normal 7 bit addresses in the start primitive.
Slave mode would still need special implementations for 10 to bit mode on each CPU though.

I don't really see any reason why a CPU driver needs to implement the _regs functions, the periph_common implementation should be equivalent. The register address is only a few bytes at most and the i2c bus is slow, so there is little to gain from streamlining it all with a single DMA transfer instead of splitting it in two transfers.

**Comment by dylad** [comment]
@gebart Yes we can use -EINVAL for invalid argument like the len params. But I'm septic for the flags. returning an EINVAL for a flag that we define in our own API is just to weird for me. 

In the current state, CPU implements must implements at least read_bytes and write_bytes which are basically the transmit and receive you were talking. I don't see a particular reason to export the start function outside of the CPU driver since we have enough control of this using the flags.

All others I2C API functions have default wrappers under drivers/periph_common/i2c.c that are #ifdef 
If the CPU want to use the default wrapper then the arch must define it (like the SPI bus in fact). You can have an example [here](https://github.com/dylad/RIOT/blob/079b8718c735353fbf754d6b89c2f9f475caeed9/cpu/sam0_common/include/periph_cpu_common.h#L49).

If for a specific reason the CPU cannot use the default wrapper (hardware limitation ? Sillicon bug ? Weird IP ?) then CPU driver can redefine each functions. 
So right know CPU drivers don't need to implement _regs functions but they can do it if it's needed.

**Comment by dylad** [comment]
@gebart I understand what you want about the API change but I'm not sure all I2C IP will be able to support this. 
You had to do some workaround for the Kinetis, I have to find some for the SAM0. As I know @basilfx also some limitations with the EFM32. And I have absolutely no idea how it looks like for the rest of CPUs.
If we are sure we can use the configuration you propose without running into lot of troubles regarding the implementations of CPU driver then I see no reason why we should not change the API again. But right know, I still doubt and this is why we made some tradeoffs.

**Comment by aabadie** [comment]
We need to take a decision regarding the API asap, otherwise we cannot proceed efficiently:
- Do we keep the function names (read/write_bytes/regs) in the API ?
- Do we use the error codes as proposed above ?
   -EIO -> I2C_DATA_NACK
   -ENXIO -> equivalent to the current I2C_ADDR_NACK
   -ETIMEDOUT -> timeout occurs before device's response
   -EOPNOTSUPP or -EINVAL -> use when a flag or operation is not supported by the driver
   -EAGAIN -> lost bus arbitration (when another master take the lead of the bus)

BTW who would like to work on the remaining CPU adaptions (CC2538, nRF) ? Maybe @smlng has some knownledge for CC2538.

It would be great to have everything adapted next week (let's be optimistic!), this way we can start the testing.

**Comment by gebart** [comment]
I can probably do hih6130, FXOS8700, ina220 later tonight

**Comment by dylad** [comment]
My position (at the moment ) is : 
-EIO -> I2C_DATA_NACK
-ENXIO -> equivalent to the current I2C_ADDR_NACK
-ETIMEDOUT -> timeout occurs before device's response
-EINVAL -> to check len > 0 or another params
-EOPNOTSUPP For unsupported flag operations
-EAGAIN -> lost bus arbitration (when another master take the lead of the bus)

Regarding the API state : I think it's safe to keep it as it right now.

All of this is debatable :)
I'll keep working on SAM0 and if I can merge it quickly I'll try the nRF52 family.

**Comment by gebart** [comment]
@dylad I think your proposal seems valid. I have updated the kinetis driver with those errnos

**Comment by dylad** [comment]
nRF52 based board has been ported to the new API in #9334

**Comment by dylad** [comment]
We have a merge conflict between new_i2c_if and the master branch caused by : 
```
boards/nucleo144-f413/Makefile.features
boards/nucleo144-f413/include/periph_conf.h 
```
@aabadie Do you know what happened ?

**Comment by aabadie** [comment]
> We have a merge conflict between new_i2c_if and the master branch

I tested locally and for me everything is ok: `git checkout master && git merge new_i2c_if` works. I also tested a rebase (git checkout new_i2c_if && git rebase master) and everything was fine.

**Comment by dylad** [comment]
Guess I've done something wrong on my side.
Sorry for the noise then !

**Comment by MrKevinWeiss** [comment]
Here are some bugs that I have found and some solutions.  

- [ ] i2c_read_bytes() with I2C_NOSTOP set in sam_common0 cpu will cause lockup.  _[Suggested Fix]_ if I2C_NOSTOP then don't wait until the bus is free.  Since the SCL line stays low due to the master at this point the bus should not be finished.
- [ ] i2c_read_bytes() with I2C_NOSTOP followed by a repeated start locks up cpu if the first bit of slave data is 0, this occurs on multiple cpus.  _[Suggested Fix]_ check if the SCL line is low before sending a start, if it isn't return an error.
- [ ] The stm32 cpu, under i2c_1.c it appears that sending to addresses that aren't there does not catch the address NACK, as a result data gets entered into the DR and a following operation will have the data offset by one.  _[Suggested Fix]_ Add a sufficient time delay before checking the status register for the NACKed bit to be set. May be related to #7846
- [ ] The stm32 cpu, under the i2c_2.c has some funny issues with what is on the line during a I2C_NOSTOP read.  The data seems find however extra bytes are clocked out due to the ACK being set by the master (which it should be since we are expecting more data).  _[Suggested Fix]_ Don't support I2C_NOSTOP read since users can then mess up a proper frame, there seems to be no practical case for which it is useful.
- [ ] Basic error messages in stm i2c implementation.  Everything seems like it is a timeout and there is more information available.  See #8461  for some fixes
- [ ] Bus initialization related to #2528.  This may be solved by moving the init to the CPU and not making it a part of the API, I need to look into it further.

**Comment by gebart** [comment]
> Bus initialization related to #2528. This may be solved by moving the init to the CPU and not making it a part of the API, I need to look into it further.

This should already be part of the i2c rework of each device driver. i2c bus initialization is performed by periph_init() at boot, and the device drivers should only do i2c_acquire during the device init.

**Comment by dylad** [comment]
> and the device drivers should only do i2c_acquire during the device init.

i2c_acquire must be used before any call of I2C API not only during the device init so we can acquire the mutex, enable peripheral, clocks, etc.

**Comment by gebart** [comment]
@dylad Sorry, I meant only i2c_acquire as opposed to i2c_init_master followed by i2c_acquire. i2c_acquire is required for all i2c bus access

**Comment by dylad** [comment]
@gebart No problem, I just want to be sure we're going in the same direction :)

**Comment by Hyungsin** [comment]
@haukepetersen, I opened #9455 for hdc1000 driver. Please update the info.

**Comment by Hyungsin** [comment]
@haukepetersen, #9457 takes care of tmp006.

**Comment by smlng** [comment]
@Hyungsin nice work! Thx for contributing!

**Comment by Hyungsin** [comment]
FYI, #9268 (fxos8700) is merged.

**Comment by dylad** [comment]
We're almost done ! only 3 remainings PR to merge !!
Unfortunately we have a merge conflict witht the following files : 
cpu/kinetis/Makefile.dep
boards/pba-d-01-kw2x/include/periph_conf.h
boards/mulle/include/periph_conf.h
boards/frdm-kw41z/include/periph_conf.h
boards/frdm-k64f/include/periph_conf.h
boards/frdm-k22f/include/periph_conf.h

and also with : 
boards/common/stm32f103c8/include/periph_conf.h

**Comment by smlng** [comment]
@dylad as you managed the rework I would suggest you clear the conflicts as soon as all drivers and stuff is in?!

**Comment by dylad** [comment]
@smlng I can give it a try. I suppose I just have to cherry-pick some commits from master.

**Comment by smlng** [comment]
mhm, no cherry-picking will not work I'd say. I think you need to rebase the `new_i2c_if` branch onto master and resolve conflicts during that. I guess we should have done the rebase during the rework several times, and best before every merge of a PR against this branch that way conflicts might have been avoidable.

**Comment by cladmi** [comment]
For me rebasing implies that you could do rebase errors (it happens all the time) and so that everything should be re-reviewed. I often saw duplicated functions on rebase due to wrong resolution.

For me the proper solution would be more to backports the PRs that introduced conflicts to the i2c branch.

**Comment by dylad** [comment]
I'll rebase the branch on master, if there is any conflict I'll backport the required changes.
Let's finish the two remaining PRs first.

**Comment by dylad** [comment]
Hmm guys I need the wise advises from a git guru here
I can rebase the new_i2c_if branch on lastest master with : 
`git rebase master`
but it failed when I do : 
`git rebase --preserve-merges master`

```
error: commit 28de4d5d0166a675d0a8e952f996545946ca36fd is a merge but no -m option was given.
fatal: cherry-pick failed
Could not pick 28de4d5d0166a675d0a8e952f996545946ca36fd
```

**Comment by smlng** [comment]
@miri64 and @cladmi can you help?

**Comment by basilfx** [comment]
It seems that `git rebase [upstream/]master --rebase-merges` (git 2.18+) works and keeps the merge commits.

**Comment by dylad** [comment]
this doesn't work on git 2.17.1 which is my default version

**Comment by cladmi** [comment]
When doing the rebase, please save here the original branch `sha1` and the new one.
It will help verifying that the difference from the commits is the same after the rebase.

**Comment by dylad** [comment]
@cladmi I think I push a clone of the new_i2c_if to the RIOT-OS repo, I'll rebase the clone and make a PR with it ? Does it suit you ?

**Comment by cladmi** [comment]
@dylad: yes doing a clone was great, this way both are kept and can be compared.
I will find the magic commands to compare them.

**Comment by dylad** [comment]
I'm closing this since the new I2C interface has been introduced :)
