### ISSUE TITLE
Track support for ST b-l475e-iot01a board

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/RIOT#7585]
Board datasheet is [here](http://www.st.com/en/evaluation-tools/b-l475e-iot01a.html), detailed pdf is [here](http://www.st.com/content/ccc/resource/technical/document/user_manual/group0/b1/b8/7a/f2/f7/8d/4b/6b/DM00347848/files/DM00347848.pdf/jcr:content/translations/en.DM00347848.pdf).

The board is based on STM32L475VG MCU.

Here is the list of missing features:

- [x] initial support (basic features: uart, spi, etc): ~#7584~
- [x] I2C support for stm32l4, ~#9202~
- [x] ADC support for stm32l4, ~#8804~ 
- [x] configure driver for HTS221 (temperature and humidity), #9716
- [x] configure driver for LIS3MDL (magnetometer), #9716
- [x] configure driver for LSM6DSL (accelerometer), #9716
- [ ] driver for LPS22HB (pressure), #10695 
- [ ] driver for VL53L0X (TOF and gesture detection)
- [ ] driver for MP34DT01 (microphone)
- [ ] driver for WiFi module Inventek ISM43362-M3G-L44
- [ ] driver for SPBTLE-RF (Bluetooth 4.1)
- [ ] driver for SPSGRF-868/915 (SubGH RF module)

**Comment by aabadie** [comment]
Tracking issue, should not be closed.

**Comment by miri64** [comment]
If they are marked as `Type: tracking`, stale bot will ignore them ;-). See https://github.com/RIOT-OS/RIOT/blob/master/.github/stale.yml#L7-L10
