### ISSUE TITLE
cbor: fix module

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#7800]
Last release tests found some quality defects in the `cbor` module (some of them known, some of them not). The following things need to happen:

- [ ] make sure the implementation is compliant with RFC 7049 (according to #7708 it is not)
- [ ] fix issues found by fuzzing (was #7708)
- [ ] move formatting to `fmt` based implementation (should fix #1891 partly)
- [ ] make sure POSIX-based functions are available on non-native platforms (was #7287 an #7411)
- [ ] remove recursion were possible
- [ ] clean-up code

Alternative approach to "fix" this issue would be to just remove it as suggested in #7708.

**Comment by gebart** [comment]
There's an alternative implementation for very constrained devices available at https://github.com/cabo/cn-cbor which may be an option if this module is dropped.

**Comment by kaspar030** [comment]
> There's an alternative implementation for very constrained devices available at https://github.com/cabo/cn-cbor which may be an option if this module is dropped.

It packaged nicely: #8025

**Comment by gebart** [comment]
@kaspar030 cool!

**Comment by kaspar030** [comment]
We should mark this module "deprecated" somehow...

**Comment by miri64** [comment]
Use `@deprecated` command in `sys/include/cbor.h` for that.

**Comment by kaspar030** [comment]
> Use @deprecated command in sys/include/cbor.h for that.

That doesn't warn when compiling, right?

**Comment by kaspar030** [comment]
I've added a note to the release notes.

**Comment by kYc0o** [comment]
Now that the module is completely deprecated (for 2 release cycles), can we close this issue?

**Comment by miri64** [comment]
It's still not removed... So I'd vote against it, but I wouldn't block a close either, if people think it should be closed.

**Comment by miri64** [comment]
Ah, but we can remove it now :-)

**Comment by kYc0o** [comment]
> Ah, but we can remove it now :-)

👍 thumbs up to remove it!

**Comment by miri64** [comment]
> +1 thumbs up to remove it!

Already asked @nmeum to rebase #8793 ;-)
