### ISSUE TITLE
tests: add pexpect scripts to enable `make test`

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#7871]
Doing the release spec tests, we found that having pexpect scripts for our tests is a good idea, as this is a first step towards automating the tests. I went now through all the tests and found, that there is a large number of them, that can easily be scripted/automated. I think it would make much sense to do so soonish, as this will save us much time down the line!

Trivial to automate:
- [x] fmt_print (#7988)
- [x] irq (#7989)
- [x] libfixmath (#8011)
- [x] libfixmath_unittests (#8011)
- [x] msg_try_receive ( #7991 )
- [x] netdev_test (#7992)
- [x] netstats_l2 (#8038)
- [x] nhdp (#7992)
- [x] pipe (#7992)
- [x] pkg_jsmn (#7992)
- [x] pkg_libcoap (#7992)
- [x] pkg_micro-ecc (#7992)
- [x] pkg_micro-ecc-with-hwrng (#7992)
- [x] pkg_minmea (#7992)
- [x] ps_schedstatistics (#7992)
- [x] pthread* , see #7906 
- [x] sched_testing (#7992)
- [x] shell (#8005)
- [x] sizeof_tcb (#7992)
- [x] ssp (#8004)
- [x] struct_tm_utility (#8008)
- [x] thread_cooperation, see #7836 
- [x] thread_exit, #7936
- [x] thread_flags, #7936
- [x] thread_flags_xtimer, #7936
- [x] thread_msg, see #7841 
- [x] thread_msg_block_w_queue, see #6720
- [x] thread_msg_block_wo_queue, see #6720
- [x] thread_msg_seq, #7936

Need some (trivial) modifications before being able to automate:
 - [x] pkg_u8g2 (#8039)
 - [x] posix_sleep (#7940) 
 - [x] trickle #7912

If we work together on this, we should be able to finish this list pretty quickly :-)

**Comment by aabadie** [comment]
Nice one!

**Comment by aabadie** [comment]
If nobody objects, I can work on the pthread tests

**Comment by smlng** [comment]
could everyone adapting a test also check if the list of blacklisted or board with insufficient memory is still up to date. I recently found that it is not, see e.g. #7836 were I reduced the number considerably.

**Comment by aabadie** [comment]
All listed tests marked above are now associated to PRs, we are getting closer.

Maybe #8036 could also be of interest for the pexpect scripts.

**Comment by cladmi** [comment]
Merged last aabadie PR to add tests.

@haukepetersen could you re-run all tests and validate everything is fixed ?

**Comment by haukepetersen** [comment]
why don't you do it yourself: https://github.com/haukepetersen/riotsandbox/blob/master/tools/tester/tester.py

**Comment by aabadie** [comment]
> why don't you do it yourself:

interesting and useful script. Why not extending the actual `testrunner` with a `run_all` function ?

**Comment by miri64** [comment]
> interesting and useful script. Why not extending the actual testrunner with a run_all function ?

@kaspar030 has some better idea to [improve the testrunner](https://github.com/RIOT-OS/RIOT/pull/7258) we rather should work towards that. ;-)

**Comment by smlng** [comment]
closing, all tracked tests are adapted

**Comment by kaspar030** [comment]
Good job to everyone involved!
