### ISSUE TITLE
periph: remove file guards from peripheral drivers

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#7981]
follow up on #7241

Since #7241 was merged, there is no need anymore for ugly file guards around peripheral driver implementations, as they are now finally only touched by the compiler if they are actually (a) included in the build (using USEMODULE) and (b) provided by a board/cpu (as in FEATURES_PROVIDED). So now it is time to clean up a little bit, and this issue should help so we don't forget anything.

Removed file guards from peripheral drivers in:
- [x] arm7_common
- [x] atmega1281
- [x] atmega2560
- [x] atmega328p
- [x] atmega_common (#8959)
- [x] cc2538 (#8955)
- [x] cc26x0
- [x] cc430
- [x] cortexm_common
- [x] efm32
- [x] ezr32wg
- [x] k22f
- [x] k60
- [x] k64f
- [x] kinetis_common (-> @gebart, #7882)
- [x] kw2xd
- [x] lm4f120 (#8958)
- [x] lpc1768 (#8956) (-> @aabadie, #8956)
- [x] lpc2387 (#8957)
- [x] mips32r2_common
- [x] mips_pic32_common
- [x] mips_pic32mx
- [x] mips_pic32mz
- [x] msp430_common
- [x] msp430fxyz
- [x] native
- [x] nrf51 (-> @haukepetersen, #7982)
- [x] nrf52 (-> @haukepetersen, #7982)
- [x] nrf5x_common (-> @haukepetersen, #7982)
- [x] sam0_common ( -> @haukepetersen, #7984)
- [x] sam3 ( -> @haukepetersen, #7984)
- [x] sam_common
- [x] samd21 ( -> @haukepetersen, #7984)
- [x] saml21 ( -> @haukepetersen, #7984)
- [x] stellaris_common
 - [x] stm32_common (-> @haukepetersen, #7983)
 - [x] stm32f0 (-> @haukepetersen, #7983)
 - [x] stm32f1 (-> @haukepetersen, #7983)
 - [x] stm32f2 (-> @haukepetersen, #7983)
 - [x] stm32f3 (-> @haukepetersen, #7983)
 - [x] stm32f4 (-> @haukepetersen, #7983)
 - [x] stm32f7 (-> @haukepetersen, #7983)
 - [x] stm32l0 (-> @haukepetersen, #7983)
 - [x] stm32l1 (-> @haukepetersen, #7983)
 - [x] stm32l4 (-> @haukepetersen, #7983)
- [x] x86

**Comment by PeterKietzmann** [comment]
All boxes checked, I'll close
