### ISSUE TITLE
crypto/ccm: bugs in the implementation of CCM mode

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#8107]
This issue summarize all the issues I have found when trying to add tests for #6706 for `sys/crypto/modes/ccm.c`

Issues shown in the PR:

* Upper bound for `auth_data_len` should be `0xFEFF`. https://tools.ietf.org/html/rfc3610 2.2 page 
* Wrong check for input plaintext message length against len encoding.
* buffer overflow if auth_data_len is larger than 26

Problems found when adding tests:
* In tests 'len_encoding' and 'mac_length' are hardwritten.
* Tests do not support `input_len` >= 256
* ccm code will break if length_encoding >= 4 (even with PR fix because of overflow).
* Code is not saving enough bytes when saving plaintext_length (off by one limit)
* CCM is broken with `input_len` >= 256 (so broken even when fixing previous point)

- [x] Refactor test to allow running other tests (https://github.com/RIOT-OS/RIOT/pull/8109)
- [x] Fix and add test for input_len check (https://github.com/RIOT-OS/RIOT/pull/8112)
- [x] Fix and add test for auth_data_len upper bound (https://github.com/RIOT-OS/RIOT/pull/8114)
- [x] Fix and add test for auth_data_len > 26
- [ ] Fix and add test for auth_data_len = 0
- [x] Fix and test for input_len >= 256
- [x] Test working on 8bit/16bit platforms…
- [x] Add all RFC/NIST tests https://github.com/RIOT-OS/RIOT/pull/12038
    - [x] Make the api take const inputs https://github.com/RIOT-OS/RIOT/pull/10376
    - split `tests-crypto` out of `unittests` (part of #12038)

This is to track and fix all what was done in https://github.com/RIOT-OS/RIOT/pull/7968.
The PRs will use and replace https://github.com/RIOT-OS/RIOT/pull/6706

**Comment by fjmolinas** [comment]
@aabadie can we check the 8bit/16bit point since #12645 is in?
