### ISSUE TITLE
GNRC MAC protocols: port to gnrc_mac module and add tutorials.

### ISSUE THREAD

**Issue by zhuoshuguo** [RIOT-OS/RIOT#8178]
This issue is mainly about a list of future works on GNRC MAC protocols and the related modules. 

So far, we have LWMAC protocol in RIOT, and will soon have GoMacH protocol. To make the codes more compact and enhance code re-usage and also remove the timer-source rely on RTT, a plan is to port both LWMAC and GoMacH to the `gnrc_mac` module. Also, we need some more detailed descriptions/instructions about the `gnrc_mac` module and the related MAC protocols, about how to use and configure them. Finally, we would like to provide a tutorial task about how to configure MAC protocols in RIOT.

# TODOs

- [ ] Merge GoMacH protocol, #[5816](https://github.com/RIOT-OS/RIOT/pull/5618);

- [ ] finish and merge the timeout module of `gnrc_mac`, #5949 ;

- [ ] totally port both GoMacH and LWMAC to `gnrc_mac`, especially for utilizing `gnrc_mac`'s timeout module for removing the rely on RTT;

- [ ] provide a detailed description and tutorial for `gnrc_mac`, which introduces its components and usages;

- [ ] provide a MAC tutorial task in RIOT's tutorials: https://github.com/RIOT-OS/Tutorials , which introduces how to configure key parameters for obtaining targeted features like low duty-cycle (channel check rate) and shorter packet transmission delay, etc.
