### ISSUE TITLE
ACU-AMNx board and MVP checklist

### ISSUE THREAD

**Issue by ZetaR60** [RIOT-OS/RIOT#9143]
### Summary:
This issue is to show progress towards support in RIOT for a new board by Acutam Automation (my company), as well as a checklist of items required to reach a minimum viable product (MVP). I also welcome any feedback anyone wishes to share here.

### Description:
The ACU-AMNx (Acutam Autonomous Mesh Node) is a field deployable IoT unit for agricultural and industrial automation. The primary target market at the moment is for Florida citrus growers, since I have some connections in that market. The goal is to be able to use a solar powered 6LoWPAN mesh network over an area of up to a few hundred acres (~a sq km) to take measurements and automate the valves and pumps. Internet uplink is currently planned to be a Linux board connected to the network that serves as a router for cell network connection.

The design strategy is have a modular system that is very flexible, and can be adapted to new uses easily. Inside the ACU-AMNx unit will be a main board providing six generic daughterboard attachment points ("slots", though they will be soldered). So, for example, solar can be swapped to primary cells or to an isolated DC-DC converter by assembling the unit with a different daughterboard. I plan to pot the whole assembly and use long lifespan components, so it will hopefully last for >10 years in the field (giving a low total cost of ownership).

An IP67 rated external port is planned to allow peripherals to be connected to provide specific sensor or actuator support. For the MVP a dielectric soil moisture sensor will be the first peripheral.

### Checklist:
Bugfixes:
- [x] Context swap fixes on ATmega. #8904 [merged]
- [x] Interrupt fixes on ATmega. #8951 [merged]
- [x] Correctly initialize clock prescaler #8952 [merged]
- [ ] Reboot loop fix on ATmega. #9141 [review]

CPU and low-level:
- [x] ATmega1284P support. #8829 [merged]
- [ ] RTT/RTC support on ATmega. #8842 [review] #8857 [review]
- [ ] RTT support for xtimer. #9308 [WIP, on hold]
- [ ] Power management support on ATmega.
- [x] EEPROM API and support on ATmega. #8862 [merged]
- [ ] PCINT support on ATmega. #7610 [rewrite]

Basic drivers:
- [x] Interrupt multiplexing. #8993 [merged]
- [ ] GPIO API change for interrupt multiplexing. #9159 [review]
- [ ] I2C GPIO expander support. #9054 [review, I2C embargo]
- [ ] Multiple interrupt support on GPIO expanders
- [ ] Better SAUL support for GPIO expanders. #9099 [WIP]
- [ ] Generic gpio_t support for GPIO expanders. #9190 [review]

External port and card drivers:
- [x] ADS101X support. #8915 [merged]
- [ ] ADS101X I2C API update. #9165 [WIP]
- [ ] 7400 series GPIO expander support.
- [ ] Moisture sensor driver.

Remote management and automation support:
- [ ] Generic API for running shell commands
- [ ] Shell command to batch other commands
- [ ] cron-like shell command to schedule other commands
- [ ] Remote shell access over the network

### Schematic:
I have decided to open-source the schematic, at least for the main board. I am uncertain about opening other parts due to my inexperience with the risks of open-source in the target market. In the case of the main board, I think that increased collaboration with RIOT and the IoT community is worth the risks.
[autonomous-mesh-node-0.7.0_schematic.pdf](https://github.com/RIOT-OS/RIOT/files/2007376/autonomous-mesh-node-0.7.0_schematic.pdf)

**Comment by aabadie** [comment]
Very nice project @ZetaR60 !

Regarding 'for EEPROM API and support on ATmega', you might be interested by #8862.
