### ISSUE TITLE
Different build behavior between `murdock` and `riot/riotbuild:latest` image

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#9645]
#### Description

Compilation behavior is different between `murdock` the `docker` image with `BUILD_IN_DOCKER=1` even with `RIOT_CI_BUILD=1`.

It makes things hard to debug and understand the root cause of problems.

Like for the following PRs:

https://github.com/RIOT-OS/RIOT/pull/9362 Warnings only on murdock
https://github.com/RIOT-OS/RIOT/pull/9605 Warnings only on murdock with llvm
https://github.com/RIOT-OS/RIOT/pull/9507 Enough memory on murdock but not in the container

#### Sub pull requests

* [x] pkg/libfixmath: replace __FILE__ by RIOT_FILE_NOPATH #9643
* [x] makefiles/docker.inc.mk: export RIOT_CI_BUILD to docker #9895
* [x] makefiles/docker.inc.mk: handle building in git worktree #10303
* [x] makefiles/docker.inc.mk: Use directories in RIOT when possible #9646
    * [x] Makefile.include: Fix BUILDRELPATH when RIOTPROJECT is CURDIR. #10302
* [x] tests/*boot: handle building in docker #11083

#### Steps to reproduce the issue

To take one as an example:

Building `tests/pkg_fatfs_vfs` for `BOARD=wsn430-v1_4` works in murdock as it is not complaining but this does not

    make -C tests/pkg_fatfs_vfs/  BOARD=wsn430-v1_4 clean all RIOT_CI_BUILD=1 BUILD_IN_DOCKER=1 DOCKER="sudo docker"

#### Expected results

It has the same behavior in docker as in murdock, so either both fail or both succeed.

#### Actual results

Murdock is ok, but in docker it fails with:

```
/data/riotbuild/riotproject/tests/pkg_fatfs_vfs/bin/wsn430-v1_4/fatfs.a(ff.o):(.debug_loc+0x1656): relocation truncated to fit: R_MSP430_16_BYTE against `no symbol'
collect2: ld returned 1 exit status
/data/riotbuild/riotbase/Makefile.include:411: recipe for target '/data/riotbuild/riotproject/tests/pkg_fatfs_vfs/bin/wsn430-v1_4/pkg_fatfs_vfs.elf' failed
make: *** [/data/riotbuild/riotproject/tests/pkg_fatfs_vfs/bin/wsn430-v1_4/pkg_fatfs_vfs.elf] Error 1
```

#### Versions

Building with docker in master.

**Comment by cladmi** [comment]
@kaspar030 @smlng I think you are the person who would know the more about it

**Comment by cladmi** [comment]
Other issue,  `RIOT_FILE_RELATIVE` is not really relative in `docker`:

```
-DRIOT_FILE_RELATIVE=\"/data/riotbuild/riotproject/tests/libfixmath_unittests/bin/pkg/stm32f0discovery/libfixmath/libfixmath/fix16_str.c\"
```

Outside I get:

```
-DRIOT_FILE_RELATIVE=\"tests/libfixmath_unittests/bin/pkg/stm32f0discovery/libfixmath/libfixmath/fix16_str.c\"
```

Which can easily explain build size difference when `RIOT_FILE_RELATIVE` is used.

**Comment by cladmi** [comment]
Also if it's possible to have an archive of the currently  used image. I could diff with my local docker image and try to find the reason.

**Comment by miri64** [comment]
At least for the LLVM thing @kaspar030 found a reason: https://github.com/RIOT-OS/RIOT/pull/9398#issuecomment-410248593

**Comment by miri64** [comment]
It appears `ccache` was also the reason for the erroneous behavior in https://github.com/RIOT-OS/RIOT/pull/9362. Can't say anything specific about https://github.com/RIOT-OS/riotdocker/pull/42 though.

**Comment by cladmi** [comment]
@ZetaR60 yes we can remove the blocking dependency.

There I have this PR here that handles some of the case for relative directories but it is also currently breaking working things: https://github.com/RIOT-OS/RIOT/pull/9646 I will try to find time to address them this week.

**Comment by cladmi** [comment]
RIOT_CI_BUILD was not exported to docker which looks like the real reason for `wsn430` not building some examples in docker.

**Comment by miri64** [comment]
The difference between the `riot/riotbuild:latest` and `murdock` worker image is now documented in https://github.com/RIOT-OS/riotdocker/tree/master/murdock-worker. Is this sufficient to close this issue?

**Comment by kaspar030** [comment]
The board doesn't exist anymore, "RIOT_CI_BUILD was not exported to docker which looks like the real reason for wsn430 not building some examples in docker.", all tasks marked done.

Also, the murdock-worker container was always based on riotdocker. If there are differences how murdock builds wrt a local build, that should be independent of Docker. If Docker builds differently than a local build, that should be independent of Murdock.

So let's close this, feel free to re-open if an issue with Murdock vs. Docker remains.
