### ISSUE TITLE
Support for self contained modules

### ISSUE THREAD

**Issue by cladmi** [RIOT-OS/RIOT#9811]
#### Description

I am working toward self contained modules outside of RIOT support with the same capabilities as a module defined in RIOT.

Currently adding a module may require to modify one of the global `Makefile.include` or `Makefile.dep` files and I would like to change this.

### Steps

* [x] make: process include and dep for external modules #8987 
* [x] make: Add 'BUILDDEPS' variable #9002 
* [ ] Allow declaring an AUTO_INIT function from within a module directory
    * [ ] core: introduce crossfile arrays (xfa), refactored #9105 
        * [ ] make: Use ld -r for intermediate linking of each module #8711 
        * [ ] cortexm: ldscript refactor #9104
* [x] Correctly handle `EXTERNAL_MODULE_DIRS` with docker https://github.com/RIOT-OS/RIOT/pull/9646
* [x] External CPU/BOARD
    * [x] Makefile.include: introduce 'BOARDSDIR' for boards directory #12183
    * [x] Makefile.include: fix board/cpu inconsistent include order #8717 
    * [x] Process dependencies before BOARD/Makefile.include TODO
        * [x] Build dependencies - processing order issues #9913
        * [x] Fix board/cpu defining dependencies in `Makefile.include` TODO
    * [x] `makefiles/arch/cortexm.inc.mk` uses `RIOTCPU` to get the common directory so cannot be reused

In the same time with the same idea, I try to also make packages self contained

* [x] pseudomodules: allow defining them in pkg/PKG/Makefile.include #9003
* [ ] WIP RFC Replace usage of USEPKG by USEMODULE. #9307 
* [ ] Move packages tests to package directory TODO (ref [tests: split unittests?](https://github.com/RIOT-OS/RIOT/issues/8941))
  * [x] packages tests moved outside of `unittests`: tests/unittests: Move large unittests to individual tests #10187

**Comment by jia200x** [comment]
awesome feature

Are you considering to include different sources? (e.g fetching a module from a github repo, from the file system or from a URL should be transparent to the builder). This way makes possible to have alternative implementation of modules that might live in a different repo

**Comment by cladmi** [comment]
That was proposed by kaspaar: https://github.com/RIOT-OS/RIOT/pull/8987#issuecomment-383043605

There are still things to solve before but could be yes.

**Comment by maribu** [comment]
Support for external modules is mature these days and part of the regular CI checks.
