### ISSUE TITLE
TF: Configuration Task Force status

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/RIOT#9856]
This issue contains the status and discussions about the recently opened RIOT [Configuration Task Force](https://github.com/RIOT-OS/RIOT/wiki/Configuration-Task-Force-%28CTF%29).

There's a [Configurations TF Project](https://github.com/RIOT-OS/RIOT/projects/22) for organizing issues and PR.

**Please link new issues/PR concerning configurations to this issue so we can easily get in sync.**

# Areas of concern
The following areas are being addressed by the CTF
### Compile-time configuration
- [ ] Declare, define and expose build-time configurations in documentation (#10138)
- [ ] Expose configurations to Kconfig (#12888)
- [x] Model features provided by CPU and Boards (#14148)

# Archives
### RIOT summit breakout session (13/09/2018)
See [comment below](https://github.com/RIOT-OS/RIOT/issues/9856#issuecomment-424007272)

### RIOT Virtual Maintainer Assembly 2020.05
Usage of Kconfig for module dependency modelling. [See discussion](https://github.com/RIOT-OS/RIOT/wiki/VMA-2020-05-minutes#kconfig-leandro--jos%C3%A9).
## Proposals
[Compile-time configuration proposal for RIOT](https://www.youtube.com/watch?v=wAXseqiCb3E) (video)

### Archived info
[Initial draft](https://gist.github.com/jia200x/73600bb0d0661598fbd2531223b79985)

**Comment by jcarrano** [comment]
> E.g CFLAGS += -DFF=default -DFF=new_value will fail.

I'd say that `CFLAGS += -DFF=some_value -DFF=conflicting_val` _will not fail_ (at compile time), instead the value will be _silently overwritten_ and that's the problem.

**Comment by jia200x** [comment]
> I'd say that CFLAGS += -DFF=some_value -DFF=conflicting_val will not fail (at compile time), instead the value will be silently overwritten and that's the problem.

Addressed. Thanks!

**Comment by jia200x** [comment]
Here's a summary of the RIOT summit breakout session:

## Minute

* The community identified the following problems:
    * Mixed build configuration and functionality (app) configuration
    * Overriding periph configuration: it's possible to copy&paste the board periph configuration in the application, but generates a lots of code duplication and doesn't allow overriding.
    * Everything gets recompiled when changing a configuration
    * App and hw configurations are not exposed, is hard to know what can be configured (specially for beginners). 
    * There is unnecesary periph configuration for some application (e.g hello world only requires 1 UART, some boards configure 3)
    * Boards don't have human-readable names, sometimes is hard to remember the actual name of a board when flashing.
    * No standard mechanism to pass app data (keys, etc)
    * No standard mechanism to configure third party packages (lwip, openthread, etc).
    * There are no API versions nor modules versions, it's not easy to know if an application will work with a given RIOT version (and it's not possible to know if it's safe to update to a new RIOT release).
    * It's possible to inject arbitrary code if configurations are handled in Makefiles.

* The following solutions/concepts were proposed to address one or more of these problems
    * Cross file arrays (#9105 )
    * High level parsers for detecting invalid configurations and modules
        * YAML (or similar) for describing dependencies and valid configuration params
    * Human Readable CLI make arguments
    * Linux tools: KConfig
    * Fetch other repositories (e.g core repo, utils repo, etc)
    * Declare configurations in header files
    * Configurations should be close to the module (so, it's easy to get rid)
    * Whatever we do, we still need to consider third party pkgs have their own configuration mechanism, which should be invoked from RIOT.

Check the original post-its based minute [here](https://gist.githubusercontent.com/jia200x/daac639c022d5b085e0019b63eadbdb0/raw/86948d9dfe50faff8d3b1d9dbeb760de0a6b9fe6/summit_bs_outcome.jpg). @leandrolanzieri did a nice transcription [here](https://gist.githubusercontent.com/jia200x/daac639c022d5b085e0019b63eadbdb0/raw/86948d9dfe50faff8d3b1d9dbeb760de0a6b9fe6/configuration_breakout_result.jpg)

You can watch the full session [via Youtube](https://www.youtube.com/watch?v=IBPHqAwLdI4&t=5013s)

## Outcome

We agreed on **start with per-module config declaration (macros) in header files**:
* It's non intrusive
* This approach could solve some of the issues exposed by the community (declare configurations, define default values, override configurations) E.g see off-line email from @kaspar030 

```
/**
 * @brief maximum number of cooks per soup
 *
 * fmt:int:min=1:max=10
 */
#ifndef CONFIG_KITCHEN_MAX_COOKS_PER_SOUP
#define CONFIG_KITCHEN_MAX_COOKS_PER_SOUP 1U
#endif
```

A tool could parse and expose these configurations to the user. 

We can always add later something on top for handling third party PKGs configurations (that have their own configuration scheme), friendly GUIs (ncurses, web based, etc) and handling dependencies and invalid cofigurations.

**Comment by MrKevinWeiss** [comment]
We can close this I suppose...
