### ISSUE TITLE
Tracker: Implement conditional compilation of GPIO IRQ based on `periph_gpio_irq` feature

### ISSUE THREAD

**Issue by haukepetersen** [RIOT-OS/RIOT#9977]
#### Description
#9845 made it possible to build GPIO drivers without support for external interrupts, very useful indeed. But sadly, except for the `cpu/msp430fxyz`, this feature is not implemented (e.g. missing ifdefs) for any other existing GPIO driver. So in other words, using the `PERIPH_GPIO_IRQ` module (or not) has no effect on most boards... 

IMHO when touching a core interface like the `periph/gpio` driver, it should be made sure that the changes are actually implemented for existing implementations (as in this case). Or at least there should be some tracking on the conversion status or similar.

Please simply close this issue if I overlooked any ongoing PR or already open issue on this topic...

GPIO implementations which need updating:
- [x] `periph/gpio.h` header fix scope of the `periph_gpio_irq` functions #9978 
- [x] Adapt `gpio_init_int` name as suggested by https://github.com/RIOT-OS/RIOT/pull/9845#issuecomment-416875712 with an alias for the old name
- [x] atmega_common - #10002 
- [x] cc2538 - #9994 
- [x] cc26x0 #9999 
- [x] efm32 - #10000 
- [x] esp8266 - #10001 
- [x] ezr32wg - #9993 
- [x] fe310 - #10007 
- [x] kinetis - #9998 
- [x] lm4f120 - #10004
- [x] lpc1768 - #9995 
- [x] lpc2387 - #9997 
- [x] msp430fxyz - ~~#9845~~ merged
- [x] native - #9976 
- [x] nrf5x_common - #10005 
- [x] sam0_common - #9996 
- [x] sam3 - #10006 
- [x] stm32_common - #10003 
- [x] stm32f1 - #10008

**Comment by gebart** [comment]
You are right in that this is only implemented for the msp430. When creating that change I only wanted to get the GPIO driver size down in order to make #8711 mergable.
Let's make this issue into the tracker for implementing this feature check on other platforms.

**Comment by gebart** [comment]
Updated the top post

**Comment by cladmi** [comment]
Some are already in https://github.com/RIOT-OS/RIOT/pull/8711 PR I will start splitting them and do the other ones.

**Comment by cladmi** [comment]
I think this belongs here https://github.com/RIOT-OS/RIOT/pull/9978

**Comment by haukepetersen** [comment]
I went through the drivers and added the fixes: #9981

**Comment by kaspar030** [comment]
> So in other words, using the `PERIPH_GPIO_IRQ` module (or not) has no effect on most boards...

Actually, using the module has the effect of also using periph_gpio.

> But sadly, except for the cpu/msp430fxyz, this feature is not implemented (e.g. missing ifdefs) for any other existing GPIO driver. 

As written [here](https://github.com/RIOT-OS/RIOT/pull/9978#issuecomment-423245763), where's the problem with that? Implementations that are "updated" only conditionally compile the irq code. The others work as before. We can now incrementally implement this optimization.

**Comment by haukepetersen** [comment]
> We can now incrementally implement this optimization.

done :-)

**Comment by haukepetersen** [comment]
everything done -> issue solved.

**Comment by cladmi** [comment]
This one has not been done yet I think ? maybe I am missing something

* [ ] Adapt gpio_init_int name as suggested by #9845 (comment) with an alias for the old name


While reviewing https://github.com/RIOT-OS/RIOT/pull/10135 I noticed that two boards `samr30-xpro` @aabadie and `lobaro-lorabox` @leandrolanzieri  do not set `periph_gpio_irq`. But they actually compile when adding `FEATURES_PROVIDED += periph_gpio_irq`. I did not run the `tests/periph_gpio` as I do not have the boards though.
As they are new boards they may have missed the update.
If that is the case, they should be updated to provide the new feature.

**Comment by leandrolanzieri** [comment]
> This one has not been done yet I think ? maybe I am missing something
> 
> * [ ]  Adapt gpio_init_int name as suggested by #9845 (comment) with an alias for the old name
> 
> While reviewing #10135 I noticed that two boards `samr30-xpro` @aabadie and `lobaro-lorabox` @leandrolanzieri do not set `periph_gpio_irq`. But they actually compile when adding `FEATURES_PROVIDED += periph_gpio_irq`. I did not run the `tests/periph_gpio` as I do not have the boards though.
> As they are new boards they may have missed the update.
> If that is the case, they should be updated to provide the new feature.

This has been addressed for the `lobaro-lorabox` now in #10449.

**Comment by cladmi** [comment]
@leandrolanzieri Cool
@aabadie can you check if it should also be done for `samr30-xpro` ?

**Comment by aabadie** [comment]
> can you check if it should also be done for samr30-xpro ?

see #10434

**Comment by PeterKietzmann** [comment]
#9845, #10434 and #10553 were all merged so I'm closing this one again
